#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 21.10-s300 (22-Aug-2021) (64 bit executable)
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Wrapper size: #Logic gates enclosing the module's instance, and bounded by key-points
# Periphery size: #Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
vpxmode
delete set_seq_merge
set_seq_merge /core/twiddle_rom_twiddle_out_reg[11]  /core/twiddle_rom_twiddle_out_reg[12] -Golden
set_seq_merge /core/twiddle_rom_twiddle_out_reg[11]  /core/twiddle_rom_twiddle_out_reg[13] -Golden
tclmode
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE fft_2_sol1_gen1_top (G) INSTANCE / (G)
# MODULE fft_2_sol1_gen1_top (R) INSTANCE / (R)
# Wrapper size: (G) = 0  (R) = 0
# Periphery size: (G) = 0  (R) = 0
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk (REP)  =   (R) clk (REP) (by name)
# IN (G) rst (REP)  =   (R) rst (REP) (by name)
# IN (G) start (REP)  =   (R) start (REP) (by name)
# IN (G) load_en (REP)  =   (R) load_en (REP) (by name)
# IN (G) load_addr[0] (REP)  =   (R) load_addr[0] (REP) (by name)
# IN (G) load_data[15] (REP)  =   (R) load_data[15] (REP) (by name)
# IN (G) load_data[14] (REP)  =   (R) load_data[14] (REP) (by name)
# IN (G) load_data[13] (REP)  =   (R) load_data[13] (REP) (by name)
# IN (G) load_data[12] (REP)  =   (R) load_data[12] (REP) (by name)
# IN (G) load_data[11] (REP)  =   (R) load_data[11] (REP) (by name)
# IN (G) load_data[10] (REP)  =   (R) load_data[10] (REP) (by name)
# IN (G) load_data[9] (REP)  =   (R) load_data[9] (REP) (by name)
# IN (G) load_data[8] (REP)  =   (R) load_data[8] (REP) (by name)
# IN (G) load_data[7] (REP)  =   (R) load_data[7] (REP) (by name)
# IN (G) load_data[6] (REP)  =   (R) load_data[6] (REP) (by name)
# IN (G) load_data[5] (REP)  =   (R) load_data[5] (REP) (by name)
# IN (G) load_data[4] (REP)  =   (R) load_data[4] (REP) (by name)
# IN (G) load_data[3] (REP)  =   (R) load_data[3] (REP) (by name)
# IN (G) load_data[2] (REP)  =   (R) load_data[2] (REP) (by name)
# IN (G) load_data[1] (REP)  =   (R) load_data[1] (REP) (by name)
# IN (G) load_data[0] (REP)  =   (R) load_data[0] (REP) (by name)
# IN (G) unload_en (REP)  =   (R) unload_en (REP) (by name)
# IN (G) unload_addr[0] (REP)  =   (R) unload_addr[0] (REP) (by name)
# IN (G) mem_rd_data[15] (REP)  =   (R) mem_rd_data[15] (REP) (by name)
# IN (G) mem_rd_data[14] (REP)  =   (R) mem_rd_data[14] (REP) (by name)
# IN (G) mem_rd_data[13] (REP)  =   (R) mem_rd_data[13] (REP) (by name)
# IN (G) mem_rd_data[12] (REP)  =   (R) mem_rd_data[12] (REP) (by name)
# IN (G) mem_rd_data[11] (REP)  =   (R) mem_rd_data[11] (REP) (by name)
# IN (G) mem_rd_data[10] (REP)  =   (R) mem_rd_data[10] (REP) (by name)
# IN (G) mem_rd_data[9] (REP)  =   (R) mem_rd_data[9] (REP) (by name)
# IN (G) mem_rd_data[8] (REP)  =   (R) mem_rd_data[8] (REP) (by name)
# IN (G) mem_rd_data[7] (REP)  =   (R) mem_rd_data[7] (REP) (by name)
# IN (G) mem_rd_data[6] (REP)  =   (R) mem_rd_data[6] (REP) (by name)
# IN (G) mem_rd_data[5] (REP)  =   (R) mem_rd_data[5] (REP) (by name)
# IN (G) mem_rd_data[4] (REP)  =   (R) mem_rd_data[4] (REP) (by name)
# IN (G) mem_rd_data[3] (REP)  =   (R) mem_rd_data[3] (REP) (by name)
# IN (G) mem_rd_data[2] (REP)  =   (R) mem_rd_data[2] (REP) (by name)
# IN (G) mem_rd_data[1] (REP)  =   (R) mem_rd_data[1] (REP) (by name)
# IN (G) mem_rd_data[0] (REP)  =   (R) mem_rd_data[0] (REP) (by name)
# RESOLVED Constraints
# OUT (G) done (REP)  =   (R) done (REP) (by name)
# OUT (G) unload_data[15] (REP)  =   (R) unload_data[15] (REP) (by name)
# OUT (G) unload_data[14] (REP)  =   (R) unload_data[14] (REP) (by name)
# OUT (G) unload_data[13] (REP)  =   (R) unload_data[13] (REP) (by name)
# OUT (G) unload_data[12] (REP)  =   (R) unload_data[12] (REP) (by name)
# OUT (G) unload_data[11] (REP)  =   (R) unload_data[11] (REP) (by name)
# OUT (G) unload_data[10] (REP)  =   (R) unload_data[10] (REP) (by name)
# OUT (G) unload_data[9] (REP)  =   (R) unload_data[9] (REP) (by name)
# OUT (G) unload_data[8] (REP)  =   (R) unload_data[8] (REP) (by name)
# OUT (G) unload_data[7] (REP)  =   (R) unload_data[7] (REP) (by name)
# OUT (G) unload_data[6] (REP)  =   (R) unload_data[6] (REP) (by name)
# OUT (G) unload_data[5] (REP)  =   (R) unload_data[5] (REP) (by name)
# OUT (G) unload_data[4] (REP)  =   (R) unload_data[4] (REP) (by name)
# OUT (G) unload_data[3] (REP)  =   (R) unload_data[3] (REP) (by name)
# OUT (G) unload_data[2] (REP)  =   (R) unload_data[2] (REP) (by name)
# OUT (G) unload_data[1] (REP)  =   (R) unload_data[1] (REP) (by name)
# OUT (G) unload_data[0] (REP)  =   (R) unload_data[0] (REP) (by name)
# OUT (G) mem_bank_sel (REP)  =   (R) mem_bank_sel (REP) (by name)
# OUT (G) mem_rd_addr[10] 0(REP)  =   (R) mem_rd_addr[10] 0(REP) (by name)
# OUT (G) mem_rd_addr[9] 0(REP)  =   (R) mem_rd_addr[9] 0(REP) (by name)
# OUT (G) mem_rd_addr[8] 0(REP)  =   (R) mem_rd_addr[8] 0(REP) (by name)
# OUT (G) mem_rd_addr[7] 0(REP)  =   (R) mem_rd_addr[7] 0(REP) (by name)
# OUT (G) mem_rd_addr[6] 0(REP)  =   (R) mem_rd_addr[6] 0(REP) (by name)
# OUT (G) mem_rd_addr[5] 0(REP)  =   (R) mem_rd_addr[5] 0(REP) (by name)
# OUT (G) mem_rd_addr[4] 0(REP)  =   (R) mem_rd_addr[4] 0(REP) (by name)
# OUT (G) mem_rd_addr[3] 0(REP)  =   (R) mem_rd_addr[3] 0(REP) (by name)
# OUT (G) mem_rd_addr[2] 0(REP)  =   (R) mem_rd_addr[2] 0(REP) (by name)
# OUT (G) mem_rd_addr[1] 0(REP)  =   (R) mem_rd_addr[1] 0(REP) (by name)
# OUT (G) mem_rd_addr[0] (REP)  =   (R) mem_rd_addr[0] (REP) (by name)
# OUT (G) mem_rd_prec 1(REP)  =   (R) mem_rd_prec 1(REP) (by name)
# OUT (G) mem_wr_en (REP)  =   (R) mem_wr_en (REP) (by name)
# OUT (G) mem_wr_addr[10] 0(REP)  =   (R) mem_wr_addr[10] 0(REP) (by name)
# OUT (G) mem_wr_addr[9] 0(REP)  =   (R) mem_wr_addr[9] 0(REP) (by name)
# OUT (G) mem_wr_addr[8] 0(REP)  =   (R) mem_wr_addr[8] 0(REP) (by name)
# OUT (G) mem_wr_addr[7] 0(REP)  =   (R) mem_wr_addr[7] 0(REP) (by name)
# OUT (G) mem_wr_addr[6] 0(REP)  =   (R) mem_wr_addr[6] 0(REP) (by name)
# OUT (G) mem_wr_addr[5] 0(REP)  =   (R) mem_wr_addr[5] 0(REP) (by name)
# OUT (G) mem_wr_addr[4] 0(REP)  =   (R) mem_wr_addr[4] 0(REP) (by name)
# OUT (G) mem_wr_addr[3] 0(REP)  =   (R) mem_wr_addr[3] 0(REP) (by name)
# OUT (G) mem_wr_addr[2] 0(REP)  =   (R) mem_wr_addr[2] 0(REP) (by name)
# OUT (G) mem_wr_addr[1] 0(REP)  =   (R) mem_wr_addr[1] 0(REP) (by name)
# OUT (G) mem_wr_addr[0] (REP)  =   (R) mem_wr_addr[0] (REP) (by name)
# OUT (G) mem_wr_data[23] (REP)  =   (R) mem_wr_data[23] (REP) (by name)
# OUT (G) mem_wr_data[22] (REP)  =   (R) mem_wr_data[22] (REP) (by name)
# OUT (G) mem_wr_data[21] (REP)  =   (R) mem_wr_data[21] (REP) (by name)
# OUT (G) mem_wr_data[20] (REP)  =   (R) mem_wr_data[20] (REP) (by name)
# OUT (G) mem_wr_data[19] (REP)  =   (R) mem_wr_data[19] (REP) (by name)
# OUT (G) mem_wr_data[18] (REP)  =   (R) mem_wr_data[18] (REP) (by name)
# OUT (G) mem_wr_data[17] (REP)  =   (R) mem_wr_data[17] (REP) (by name)
# OUT (G) mem_wr_data[16] (REP)  =   (R) mem_wr_data[16] (REP) (by name)
# OUT (G) mem_wr_data[15] (REP)  =   (R) mem_wr_data[15] (REP) (by name)
# OUT (G) mem_wr_data[14] (REP)  =   (R) mem_wr_data[14] (REP) (by name)
# OUT (G) mem_wr_data[13] (REP)  =   (R) mem_wr_data[13] (REP) (by name)
# OUT (G) mem_wr_data[12] (REP)  =   (R) mem_wr_data[12] (REP) (by name)
# OUT (G) mem_wr_data[11] (REP)  =   (R) mem_wr_data[11] (REP) (by name)
# OUT (G) mem_wr_data[10] (REP)  =   (R) mem_wr_data[10] (REP) (by name)
# OUT (G) mem_wr_data[9] (REP)  =   (R) mem_wr_data[9] (REP) (by name)
# OUT (G) mem_wr_data[8] (REP)  =   (R) mem_wr_data[8] (REP) (by name)
# OUT (G) mem_wr_data[7] (REP)  =   (R) mem_wr_data[7] (REP) (by name)
# OUT (G) mem_wr_data[6] (REP)  =   (R) mem_wr_data[6] (REP) (by name)
# OUT (G) mem_wr_data[5] (REP)  =   (R) mem_wr_data[5] (REP) (by name)
# OUT (G) mem_wr_data[4] (REP)  =   (R) mem_wr_data[4] (REP) (by name)
# OUT (G) mem_wr_data[3] (REP)  =   (R) mem_wr_data[3] (REP) (by name)
# OUT (G) mem_wr_data[2] (REP)  =   (R) mem_wr_data[2] (REP) (by name)
# OUT (G) mem_wr_data[1] (REP)  =   (R) mem_wr_data[1] (REP) (by name)
# OUT (G) mem_wr_data[0] (REP)  =   (R) mem_wr_data[0] (REP) (by name)
set_root_module fft_2_sol1_gen1_top -Golden
set_root_module fft_2_sol1_gen1_top -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
# Constraint commands 
add_output_stuck_at 0 {mem_rd_addr[10]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[9]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[8]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[7]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[6]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[5]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[4]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[3]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[2]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[1]} -Golden -hier
add_output_stuck_at 1 mem_rd_prec -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[10]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[9]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[8]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[7]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[6]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[5]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[4]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[3]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[2]} -Golden -hier
add_output_stuck_at 0 {mem_wr_addr[1]} -Golden -hier
add_output_stuck_at 0 {mem_rd_addr[10]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[9]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[8]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[7]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[6]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[5]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[4]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[3]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[2]} -Revised -hier
add_output_stuck_at 0 {mem_rd_addr[1]} -Revised -hier
add_output_stuck_at 1 mem_rd_prec -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[10]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[9]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[8]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[7]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[6]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[5]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[4]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[3]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[2]} -Revised -hier
add_output_stuck_at 0 {mem_wr_addr[1]} -Revised -hier
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
#-------------------------------------------------------------------------------
# VERBOSE REPORTING
#-------------------------------------------------------------------------------
# The following Golden modules are not written because of non-matching
# instance names in Revised:
# fp8_mul (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/cmul_inst/m1) (G)
# fp8_cmul (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/cmul_inst) (G)
# fp8_mul_0 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/cmul_inst/m2) (G)
# fp8_add_sub_2_0 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/sub_inst/adder_imag) (G)
# fp8_mul_1 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/cmul_inst/m3) (G)
# fft_2_sol1_gen1_core_MAX_N1024_ADDR_WIDTH11 (Instance: core) (G)
# fp8_complex_add_sub (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/adder_inst) (G)
# fp8_mul_2 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/cmul_inst/m4) (G)
# fp8_add_sub_0 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/cmul_inst/a1) (G)
# complex_fp8_to_fp4 (Instance: core/rd_conv_down) (G)
# twiddle_factor_unified_synthesizable_MAX_N1024_ADDR_WIDTH11 (Instance: core/twiddle_rom) (G)
# fp8_butterfly_generation_unit (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst) (G)
# fp8_add_sub_1 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/adder_inst/adder_real) (G)
# fp8_complex_add_sub_0 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/sub_inst) (G)
# dit_fft_agu_variable_MAX_N1024_ADDR_WIDTH11 (Instance: core/agu) (G)
# bit_reverse_MAX_N1024_WIDTH11 (Instance: br) (G)
# fp8_add_sub_2 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/adder_inst/adder_imag) (G)
# fp8_add_sub (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/cmul_inst/s1) (G)
# fp8_add_sub_1_0 (Instance: core/bf_st0/USE_PURE_FP8.fp8_butterfly_inst/sub_inst/adder_real) (G)
# butterfly_wrapper_MULT_PRECISION1_ADD_PRECISION1 (Instance: core/bf_st0) (G)
# complex_fp4_to_fp8 (Instance: core/rd_conv_up) (G)
#-------------------------------------------------------------------------------
# _END_OF_LEC_HIERARCHICAL_DOFILE_
