// =============================================================================
// FP32 Twiddle Factor ROM -- synthesizable case-statement version
// =============================================================================
// AUTO-GENERATED by generate_fp32_twiddles.py -- do not hand-edit the ROM
// table below; re-run the generator instead.
//
// Mirrors twiddle_factor_unified in verilog_sources/twiddle_rom_synthesizable.v:
// same dynamic k-scaling for runtime N, same half-plane symmetry +
// conjugation, same hardcoded -1.0 midpoint. The stored word is 64-bit
// complex FP32 instead of the 24-bit unified FP8+FP4 word, and there is no
// PRECISION port.
//
// ROM word format: [63:32] FP32 Real, [31:0] FP32 Imag
//
// FIX (synthesis): replaced the $readmemb-based memory with a fully
// synthesizable registered-case ROM. All 512 entries are sourced
// directly from twiddles_fp32_1024.txt (authoritative) via
// generate_fp32_twiddles.py. Yosys/OpenROAD infer this as a ROM mapped to
// library cells -- no external file dependency at synthesis time, no
// working-directory-relative path to get wrong.
//
// Conjugate symmetry: only k=0..511 are stored.
//   W_N^{N-k} = conj(W_N^k) -> second half handled by flipping the
//   imaginary sign bit. k=512 (W=-1+0j) is hardcoded separately.
//
// Internally 1-cycle pipelined at the address/lookup boundary (register
// between "2. Symmetry Logic" and "3. ROM"): a single flat 512-way
// case statement measured (on the FP16 baseline's identical structure, on a
// real post-route netlist) as a ~40-gate-deep combinational chain (not the
// balanced ~log2(512)-level tree a well-structured mux would give
// -- Yosys/ABC do not automatically balance one huge flat case with fully
// arbitrary constants and no sharing opportunity). The lookup below is
// therefore written as an explicit 16-way outer selection over
// 16 independent 32-way inner blocks
// (rom_addr[8:5] picks the block,
// rom_addr[4:0] picks within it), still fully combinational
// and still inside the same single post-register cycle -- this just gives
// the synthesis tool a hierarchy to map onto instead of one flat
// 512-way structure, bounding each stage's depth to a
// 32-way / 16-way mux. The caller must add 1
// matching cycle to its alignment pipeline for the address/lookup register
// -- see TWIDDLE_LATENCY in fp32_template_generator.py.
// =============================================================================

module twiddle_factor_fp32 #(
    parameter MAX_N      = 1024,
    parameter ADDR_WIDTH = $clog2(MAX_N) + 1
)(
    input                    clk,
    input  [ADDR_WIDTH-1:0] k,            // Index k
    input  [ADDR_WIDTH-1:0] n,            // Current FFT size N
    output reg [63:0]       twiddle_out
);

    // --------------------------------------------------------
    // 1. Dynamic Scaling Logic
    // --------------------------------------------------------
    reg [ADDR_WIDTH-1:0] scaled_k;

    always @(*) begin
        case (n)
            1024: scaled_k = k;
            512:  scaled_k = {k, 1'b0};         // k * 2
            256:  scaled_k = {k, 2'b00};        // k * 4
            128:  scaled_k = {k, 3'b000};       // k * 8
            64:   scaled_k = {k, 4'b0000};      // k * 16
            32:   scaled_k = {k, 5'b00000};     // k * 32
            16:   scaled_k = {k, 6'b000000};    // k * 64
            8:    scaled_k = {k, 7'b0000000};   // k * 128
            4:    scaled_k = {k, 8'b00000000};  // k * 256
            2:    scaled_k = {k, 9'b000000000}; // k * 512
            default: scaled_k = 11'd0;
        endcase
    end

    // --------------------------------------------------------
    // 2. Symmetry Logic
    // --------------------------------------------------------
    reg        use_conjugate_w;
    reg [9:0]  rom_addr_w;       // Address within the 0-511 block
    reg        is_midpoint_w;

    always @(*) begin
        is_midpoint_w = 1'b0;

        if (scaled_k == 512) begin
            // 180 degrees is a boundary case
            is_midpoint_w   = 1'b1;
            rom_addr_w      = 0;
            use_conjugate_w = 1'b0;
        end
        else if (scaled_k > 511) begin
            // Second half (180 < angle < 360) -> Symmetry
            rom_addr_w      = 1024 - scaled_k;
            use_conjugate_w = 1'b1;
        end
        else begin
            // First half (0 <= angle < 180)
            rom_addr_w      = scaled_k;
            use_conjugate_w = 1'b0;
        end
    end

    // ---- pipeline register: address computation | ROM lookup ----
    reg        use_conjugate;
    reg [9:0]  rom_addr;
    reg        is_midpoint;

    always @(posedge clk) begin
        use_conjugate <= use_conjugate_w;
        rom_addr      <= rom_addr_w;
        is_midpoint   <= is_midpoint_w;
    end

    // --------------------------------------------------------
    // 3. ROM -- 512 entries as 16 independent
    //    32-way combinational blocks, outer-selected by
    //    rom_addr[8:5]. See header comment for why.
    // --------------------------------------------------------
    reg [63:0] block_data [0:15];

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[0] = 64'h3F80000000000000;
            5'd1: block_data[0] = 64'h3F7FFEC4BBC90F88;
            5'd2: block_data[0] = 64'h3F7FFB11BC490E90;
            5'd3: block_data[0] = 64'h3F7FF4E6BC96C9B6;
            5'd4: block_data[0] = 64'h3F7FEC43BCC90AB0;
            5'd5: block_data[0] = 64'h3F7FE129BCFB49BA;
            5'd6: block_data[0] = 64'h3F7FD397BD16C32C;
            5'd7: block_data[0] = 64'h3F7FC38FBD2FE007;
            5'd8: block_data[0] = 64'h3F7FB10FBD48FB30;
            5'd9: block_data[0] = 64'h3F7F9C18BD621469;
            5'd10: block_data[0] = 64'h3F7F84ABBD7B2B74;
            5'd11: block_data[0] = 64'h3F7F6AC7BD8A200A;
            5'd12: block_data[0] = 64'h3F7F4E6DBD96A905;
            5'd13: block_data[0] = 64'h3F7F2F9DBDA3308C;
            5'd14: block_data[0] = 64'h3F7F0E58BDAFB680;
            5'd15: block_data[0] = 64'h3F7EEA9DBDBC3AC3;
            5'd16: block_data[0] = 64'h3F7EC46DBDC8BD36;
            5'd17: block_data[0] = 64'h3F7E9BC9BDD53DB9;
            5'd18: block_data[0] = 64'h3F7E70B0BDE1BC2E;
            5'd19: block_data[0] = 64'h3F7E4323BDEE3876;
            5'd20: block_data[0] = 64'h3F7E1324BDFAB273;
            5'd21: block_data[0] = 64'h3F7DE0B1BE039502;
            5'd22: block_data[0] = 64'h3F7DABCCBE09CF86;
            5'd23: block_data[0] = 64'h3F7D7474BE1008B7;
            5'd24: block_data[0] = 64'h3F7D3AACBE164083;
            5'd25: block_data[0] = 64'h3F7CFE73BE1C76DE;
            5'd26: block_data[0] = 64'h3F7CBFC9BE22ABB6;
            5'd27: block_data[0] = 64'h3F7C7EB0BE28DEFC;
            5'd28: block_data[0] = 64'h3F7C3B28BE2F10A2;
            5'd29: block_data[0] = 64'h3F7BF531BE354098;
            5'd30: block_data[0] = 64'h3F7BACCDBE3B6ECF;
            5'd31: block_data[0] = 64'h3F7B61FCBE419B37;
            default: block_data[0] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[1] = 64'h3F7B14BEBE47C5C2;
            5'd1: block_data[1] = 64'h3F7AC516BE4DEE60;
            5'd2: block_data[1] = 64'h3F7A7302BE541501;
            5'd3: block_data[1] = 64'h3F7A1E84BE5A3997;
            5'd4: block_data[1] = 64'h3F79C79DBE605C13;
            5'd5: block_data[1] = 64'h3F796E4EBE667C66;
            5'd6: block_data[1] = 64'h3F791298BE6C9A7F;
            5'd7: block_data[1] = 64'h3F78B47BBE72B651;
            5'd8: block_data[1] = 64'h3F7853F8BE78CFCC;
            5'd9: block_data[1] = 64'h3F77F110BE7EE6E1;
            5'd10: block_data[1] = 64'h3F778BC5BE827DC0;
            5'd11: block_data[1] = 64'h3F772417BE8586CE;
            5'd12: block_data[1] = 64'h3F76BA07BE888E93;
            5'd13: block_data[1] = 64'h3F764D97BE8B9507;
            5'd14: block_data[1] = 64'h3F75DEC6BE8E9A22;
            5'd15: block_data[1] = 64'h3F756D97BE919DDD;
            5'd16: block_data[1] = 64'h3F74FA0BBE94A031;
            5'd17: block_data[1] = 64'h3F748422BE97A117;
            5'd18: block_data[1] = 64'h3F740BDDBE9AA086;
            5'd19: block_data[1] = 64'h3F73913FBE9D9E78;
            5'd20: block_data[1] = 64'h3F731447BEA09AE5;
            5'd21: block_data[1] = 64'h3F7294F8BEA395C5;
            5'd22: block_data[1] = 64'h3F721352BEA68F12;
            5'd23: block_data[1] = 64'h3F718F57BEA986C4;
            5'd24: block_data[1] = 64'h3F710908BEAC7CD4;
            5'd25: block_data[1] = 64'h3F708066BEAF713A;
            5'd26: block_data[1] = 64'h3F6FF573BEB263EF;
            5'd27: block_data[1] = 64'h3F6F6830BEB554EC;
            5'd28: block_data[1] = 64'h3F6ED89EBEB8442A;
            5'd29: block_data[1] = 64'h3F6E46BEBEBB31A0;
            5'd30: block_data[1] = 64'h3F6DB293BEBE1D4A;
            5'd31: block_data[1] = 64'h3F6D1C1DBEC1071E;
            default: block_data[1] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[2] = 64'h3F6C835EBEC3EF15;
            5'd1: block_data[2] = 64'h3F6BE858BEC6D529;
            5'd2: block_data[2] = 64'h3F6B4B0CBEC9B953;
            5'd3: block_data[2] = 64'h3F6AAB7BBECC9B8B;
            5'd4: block_data[2] = 64'h3F6A09A7BECF7BCA;
            5'd5: block_data[2] = 64'h3F696591BED25A09;
            5'd6: block_data[2] = 64'h3F68BF3CBED53641;
            5'd7: block_data[2] = 64'h3F6816A8BED8106B;
            5'd8: block_data[2] = 64'h3F676BD8BEDAE880;
            5'd9: block_data[2] = 64'h3F66BECCBEDDBE79;
            5'd10: block_data[2] = 64'h3F660F88BEE0924F;
            5'd11: block_data[2] = 64'h3F655E0BBEE363FA;
            5'd12: block_data[2] = 64'h3F64AA59BEE63375;
            5'd13: block_data[2] = 64'h3F63F473BEE900B7;
            5'd14: block_data[2] = 64'h3F633C5ABEEBCBBB;
            5'd15: block_data[2] = 64'h3F628210BEEE9479;
            5'd16: block_data[2] = 64'h3F61C598BEF15AEA;
            5'd17: block_data[2] = 64'h3F6106F2BEF41F07;
            5'd18: block_data[2] = 64'h3F604621BEF6E0CB;
            5'd19: block_data[2] = 64'h3F5F8327BEF9A02D;
            5'd20: block_data[2] = 64'h3F5EBE05BEFC5D27;
            5'd21: block_data[2] = 64'h3F5DF6BEBEFF17B2;
            5'd22: block_data[2] = 64'h3F5D2D53BF00E7E4;
            5'd23: block_data[2] = 64'h3F5C61C7BF0242B1;
            5'd24: block_data[2] = 64'h3F5B941ABF039C3D;
            5'd25: block_data[2] = 64'h3F5AC450BF04F484;
            5'd26: block_data[2] = 64'h3F59F26ABF064B82;
            5'd27: block_data[2] = 64'h3F591E6ABF07A136;
            5'd28: block_data[2] = 64'h3F584853BF08F59B;
            5'd29: block_data[2] = 64'h3F577026BF0A48AD;
            5'd30: block_data[2] = 64'h3F5695E5BF0B9A6B;
            5'd31: block_data[2] = 64'h3F55B993BF0CEAD0;
            default: block_data[2] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[3] = 64'h3F54DB31BF0E39DA;
            5'd1: block_data[3] = 64'h3F53FAC3BF0F8784;
            5'd2: block_data[3] = 64'h3F531849BF10D3CD;
            5'd3: block_data[3] = 64'h3F5233C6BF121EB0;
            5'd4: block_data[3] = 64'h3F514D3DBF13682A;
            5'd5: block_data[3] = 64'h3F5064AFBF14B039;
            5'd6: block_data[3] = 64'h3F4F7A1FBF15F6D9;
            5'd7: block_data[3] = 64'h3F4E8D90BF173C07;
            5'd8: block_data[3] = 64'h3F4D9F02BF187FC0;
            5'd9: block_data[3] = 64'h3F4CAE79BF19C200;
            5'd10: block_data[3] = 64'h3F4BBBF8BF1B02C6;
            5'd11: block_data[3] = 64'h3F4AC77FBF1C420C;
            5'd12: block_data[3] = 64'h3F49D112BF1D7FD1;
            5'd13: block_data[3] = 64'h3F48D8B3BF1EBC12;
            5'd14: block_data[3] = 64'h3F47DE65BF1FF6CB;
            5'd15: block_data[3] = 64'h3F46E22ABF212FF9;
            5'd16: block_data[3] = 64'h3F45E403BF226799;
            5'd17: block_data[3] = 64'h3F44E3F5BF239DA9;
            5'd18: block_data[3] = 64'h3F43E200BF24D225;
            5'd19: block_data[3] = 64'h3F42DE29BF26050A;
            5'd20: block_data[3] = 64'h3F41D870BF273656;
            5'd21: block_data[3] = 64'h3F40D0DABF286605;
            5'd22: block_data[3] = 64'h3F3FC767BF299415;
            5'd23: block_data[3] = 64'h3F3EBC1BBF2AC082;
            5'd24: block_data[3] = 64'h3F3DAEF9BF2BEB4A;
            5'd25: block_data[3] = 64'h3F3CA003BF2D1469;
            5'd26: block_data[3] = 64'h3F3B8F3BBF2E3BDE;
            5'd27: block_data[3] = 64'h3F3A7CA4BF2F61A5;
            5'd28: block_data[3] = 64'h3F396842BF3085BB;
            5'd29: block_data[3] = 64'h3F385216BF31A81D;
            5'd30: block_data[3] = 64'h3F373A23BF32C8C9;
            5'd31: block_data[3] = 64'h3F36206CBF33E7BC;
            default: block_data[3] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[4] = 64'h3F3504F3BF3504F3;
            5'd1: block_data[4] = 64'h3F33E7BCBF36206C;
            5'd2: block_data[4] = 64'h3F32C8C9BF373A23;
            5'd3: block_data[4] = 64'h3F31A81DBF385216;
            5'd4: block_data[4] = 64'h3F3085BBBF396842;
            5'd5: block_data[4] = 64'h3F2F61A5BF3A7CA4;
            5'd6: block_data[4] = 64'h3F2E3BDEBF3B8F3B;
            5'd7: block_data[4] = 64'h3F2D1469BF3CA003;
            5'd8: block_data[4] = 64'h3F2BEB4ABF3DAEF9;
            5'd9: block_data[4] = 64'h3F2AC082BF3EBC1B;
            5'd10: block_data[4] = 64'h3F299415BF3FC767;
            5'd11: block_data[4] = 64'h3F286605BF40D0DA;
            5'd12: block_data[4] = 64'h3F273656BF41D870;
            5'd13: block_data[4] = 64'h3F26050ABF42DE29;
            5'd14: block_data[4] = 64'h3F24D225BF43E200;
            5'd15: block_data[4] = 64'h3F239DA9BF44E3F5;
            5'd16: block_data[4] = 64'h3F226799BF45E403;
            5'd17: block_data[4] = 64'h3F212FF9BF46E22A;
            5'd18: block_data[4] = 64'h3F1FF6CBBF47DE65;
            5'd19: block_data[4] = 64'h3F1EBC12BF48D8B3;
            5'd20: block_data[4] = 64'h3F1D7FD1BF49D112;
            5'd21: block_data[4] = 64'h3F1C420CBF4AC77F;
            5'd22: block_data[4] = 64'h3F1B02C6BF4BBBF8;
            5'd23: block_data[4] = 64'h3F19C200BF4CAE79;
            5'd24: block_data[4] = 64'h3F187FC0BF4D9F02;
            5'd25: block_data[4] = 64'h3F173C07BF4E8D90;
            5'd26: block_data[4] = 64'h3F15F6D9BF4F7A1F;
            5'd27: block_data[4] = 64'h3F14B039BF5064AF;
            5'd28: block_data[4] = 64'h3F13682ABF514D3D;
            5'd29: block_data[4] = 64'h3F121EB0BF5233C6;
            5'd30: block_data[4] = 64'h3F10D3CDBF531849;
            5'd31: block_data[4] = 64'h3F0F8784BF53FAC3;
            default: block_data[4] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[5] = 64'h3F0E39DABF54DB31;
            5'd1: block_data[5] = 64'h3F0CEAD0BF55B993;
            5'd2: block_data[5] = 64'h3F0B9A6BBF5695E5;
            5'd3: block_data[5] = 64'h3F0A48ADBF577026;
            5'd4: block_data[5] = 64'h3F08F59BBF584853;
            5'd5: block_data[5] = 64'h3F07A136BF591E6A;
            5'd6: block_data[5] = 64'h3F064B82BF59F26A;
            5'd7: block_data[5] = 64'h3F04F484BF5AC450;
            5'd8: block_data[5] = 64'h3F039C3DBF5B941A;
            5'd9: block_data[5] = 64'h3F0242B1BF5C61C7;
            5'd10: block_data[5] = 64'h3F00E7E4BF5D2D53;
            5'd11: block_data[5] = 64'h3EFF17B2BF5DF6BE;
            5'd12: block_data[5] = 64'h3EFC5D27BF5EBE05;
            5'd13: block_data[5] = 64'h3EF9A02DBF5F8327;
            5'd14: block_data[5] = 64'h3EF6E0CBBF604621;
            5'd15: block_data[5] = 64'h3EF41F07BF6106F2;
            5'd16: block_data[5] = 64'h3EF15AEABF61C598;
            5'd17: block_data[5] = 64'h3EEE9479BF628210;
            5'd18: block_data[5] = 64'h3EEBCBBBBF633C5A;
            5'd19: block_data[5] = 64'h3EE900B7BF63F473;
            5'd20: block_data[5] = 64'h3EE63375BF64AA59;
            5'd21: block_data[5] = 64'h3EE363FABF655E0B;
            5'd22: block_data[5] = 64'h3EE0924FBF660F88;
            5'd23: block_data[5] = 64'h3EDDBE79BF66BECC;
            5'd24: block_data[5] = 64'h3EDAE880BF676BD8;
            5'd25: block_data[5] = 64'h3ED8106BBF6816A8;
            5'd26: block_data[5] = 64'h3ED53641BF68BF3C;
            5'd27: block_data[5] = 64'h3ED25A09BF696591;
            5'd28: block_data[5] = 64'h3ECF7BCABF6A09A7;
            5'd29: block_data[5] = 64'h3ECC9B8BBF6AAB7B;
            5'd30: block_data[5] = 64'h3EC9B953BF6B4B0C;
            5'd31: block_data[5] = 64'h3EC6D529BF6BE858;
            default: block_data[5] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[6] = 64'h3EC3EF15BF6C835E;
            5'd1: block_data[6] = 64'h3EC1071EBF6D1C1D;
            5'd2: block_data[6] = 64'h3EBE1D4ABF6DB293;
            5'd3: block_data[6] = 64'h3EBB31A0BF6E46BE;
            5'd4: block_data[6] = 64'h3EB8442ABF6ED89E;
            5'd5: block_data[6] = 64'h3EB554ECBF6F6830;
            5'd6: block_data[6] = 64'h3EB263EFBF6FF573;
            5'd7: block_data[6] = 64'h3EAF713ABF708066;
            5'd8: block_data[6] = 64'h3EAC7CD4BF710908;
            5'd9: block_data[6] = 64'h3EA986C4BF718F57;
            5'd10: block_data[6] = 64'h3EA68F12BF721352;
            5'd11: block_data[6] = 64'h3EA395C5BF7294F8;
            5'd12: block_data[6] = 64'h3EA09AE5BF731447;
            5'd13: block_data[6] = 64'h3E9D9E78BF73913F;
            5'd14: block_data[6] = 64'h3E9AA086BF740BDD;
            5'd15: block_data[6] = 64'h3E97A117BF748422;
            5'd16: block_data[6] = 64'h3E94A031BF74FA0B;
            5'd17: block_data[6] = 64'h3E919DDDBF756D97;
            5'd18: block_data[6] = 64'h3E8E9A22BF75DEC6;
            5'd19: block_data[6] = 64'h3E8B9507BF764D97;
            5'd20: block_data[6] = 64'h3E888E93BF76BA07;
            5'd21: block_data[6] = 64'h3E8586CEBF772417;
            5'd22: block_data[6] = 64'h3E827DC0BF778BC5;
            5'd23: block_data[6] = 64'h3E7EE6E1BF77F110;
            5'd24: block_data[6] = 64'h3E78CFCCBF7853F8;
            5'd25: block_data[6] = 64'h3E72B651BF78B47B;
            5'd26: block_data[6] = 64'h3E6C9A7FBF791298;
            5'd27: block_data[6] = 64'h3E667C66BF796E4E;
            5'd28: block_data[6] = 64'h3E605C13BF79C79D;
            5'd29: block_data[6] = 64'h3E5A3997BF7A1E84;
            5'd30: block_data[6] = 64'h3E541501BF7A7302;
            5'd31: block_data[6] = 64'h3E4DEE60BF7AC516;
            default: block_data[6] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[7] = 64'h3E47C5C2BF7B14BE;
            5'd1: block_data[7] = 64'h3E419B37BF7B61FC;
            5'd2: block_data[7] = 64'h3E3B6ECFBF7BACCD;
            5'd3: block_data[7] = 64'h3E354098BF7BF531;
            5'd4: block_data[7] = 64'h3E2F10A2BF7C3B28;
            5'd5: block_data[7] = 64'h3E28DEFCBF7C7EB0;
            5'd6: block_data[7] = 64'h3E22ABB6BF7CBFC9;
            5'd7: block_data[7] = 64'h3E1C76DEBF7CFE73;
            5'd8: block_data[7] = 64'h3E164083BF7D3AAC;
            5'd9: block_data[7] = 64'h3E1008B7BF7D7474;
            5'd10: block_data[7] = 64'h3E09CF86BF7DABCC;
            5'd11: block_data[7] = 64'h3E039502BF7DE0B1;
            5'd12: block_data[7] = 64'h3DFAB273BF7E1324;
            5'd13: block_data[7] = 64'h3DEE3876BF7E4323;
            5'd14: block_data[7] = 64'h3DE1BC2EBF7E70B0;
            5'd15: block_data[7] = 64'h3DD53DB9BF7E9BC9;
            5'd16: block_data[7] = 64'h3DC8BD36BF7EC46D;
            5'd17: block_data[7] = 64'h3DBC3AC3BF7EEA9D;
            5'd18: block_data[7] = 64'h3DAFB680BF7F0E58;
            5'd19: block_data[7] = 64'h3DA3308CBF7F2F9D;
            5'd20: block_data[7] = 64'h3D96A905BF7F4E6D;
            5'd21: block_data[7] = 64'h3D8A200ABF7F6AC7;
            5'd22: block_data[7] = 64'h3D7B2B74BF7F84AB;
            5'd23: block_data[7] = 64'h3D621469BF7F9C18;
            5'd24: block_data[7] = 64'h3D48FB30BF7FB10F;
            5'd25: block_data[7] = 64'h3D2FE007BF7FC38F;
            5'd26: block_data[7] = 64'h3D16C32CBF7FD397;
            5'd27: block_data[7] = 64'h3CFB49BABF7FE129;
            5'd28: block_data[7] = 64'h3CC90AB0BF7FEC43;
            5'd29: block_data[7] = 64'h3C96C9B6BF7FF4E6;
            5'd30: block_data[7] = 64'h3C490E90BF7FFB11;
            5'd31: block_data[7] = 64'h3BC90F88BF7FFEC4;
            default: block_data[7] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[8] = 64'h248D3132BF800000;
            5'd1: block_data[8] = 64'hBBC90F88BF7FFEC4;
            5'd2: block_data[8] = 64'hBC490E90BF7FFB11;
            5'd3: block_data[8] = 64'hBC96C9B6BF7FF4E6;
            5'd4: block_data[8] = 64'hBCC90AB0BF7FEC43;
            5'd5: block_data[8] = 64'hBCFB49BABF7FE129;
            5'd6: block_data[8] = 64'hBD16C32CBF7FD397;
            5'd7: block_data[8] = 64'hBD2FE007BF7FC38F;
            5'd8: block_data[8] = 64'hBD48FB30BF7FB10F;
            5'd9: block_data[8] = 64'hBD621469BF7F9C18;
            5'd10: block_data[8] = 64'hBD7B2B74BF7F84AB;
            5'd11: block_data[8] = 64'hBD8A200ABF7F6AC7;
            5'd12: block_data[8] = 64'hBD96A905BF7F4E6D;
            5'd13: block_data[8] = 64'hBDA3308CBF7F2F9D;
            5'd14: block_data[8] = 64'hBDAFB680BF7F0E58;
            5'd15: block_data[8] = 64'hBDBC3AC3BF7EEA9D;
            5'd16: block_data[8] = 64'hBDC8BD36BF7EC46D;
            5'd17: block_data[8] = 64'hBDD53DB9BF7E9BC9;
            5'd18: block_data[8] = 64'hBDE1BC2EBF7E70B0;
            5'd19: block_data[8] = 64'hBDEE3876BF7E4323;
            5'd20: block_data[8] = 64'hBDFAB273BF7E1324;
            5'd21: block_data[8] = 64'hBE039502BF7DE0B1;
            5'd22: block_data[8] = 64'hBE09CF86BF7DABCC;
            5'd23: block_data[8] = 64'hBE1008B7BF7D7474;
            5'd24: block_data[8] = 64'hBE164083BF7D3AAC;
            5'd25: block_data[8] = 64'hBE1C76DEBF7CFE73;
            5'd26: block_data[8] = 64'hBE22ABB6BF7CBFC9;
            5'd27: block_data[8] = 64'hBE28DEFCBF7C7EB0;
            5'd28: block_data[8] = 64'hBE2F10A2BF7C3B28;
            5'd29: block_data[8] = 64'hBE354098BF7BF531;
            5'd30: block_data[8] = 64'hBE3B6ECFBF7BACCD;
            5'd31: block_data[8] = 64'hBE419B37BF7B61FC;
            default: block_data[8] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[9] = 64'hBE47C5C2BF7B14BE;
            5'd1: block_data[9] = 64'hBE4DEE60BF7AC516;
            5'd2: block_data[9] = 64'hBE541501BF7A7302;
            5'd3: block_data[9] = 64'hBE5A3997BF7A1E84;
            5'd4: block_data[9] = 64'hBE605C13BF79C79D;
            5'd5: block_data[9] = 64'hBE667C66BF796E4E;
            5'd6: block_data[9] = 64'hBE6C9A7FBF791298;
            5'd7: block_data[9] = 64'hBE72B651BF78B47B;
            5'd8: block_data[9] = 64'hBE78CFCCBF7853F8;
            5'd9: block_data[9] = 64'hBE7EE6E1BF77F110;
            5'd10: block_data[9] = 64'hBE827DC0BF778BC5;
            5'd11: block_data[9] = 64'hBE8586CEBF772417;
            5'd12: block_data[9] = 64'hBE888E93BF76BA07;
            5'd13: block_data[9] = 64'hBE8B9507BF764D97;
            5'd14: block_data[9] = 64'hBE8E9A22BF75DEC6;
            5'd15: block_data[9] = 64'hBE919DDDBF756D97;
            5'd16: block_data[9] = 64'hBE94A031BF74FA0B;
            5'd17: block_data[9] = 64'hBE97A117BF748422;
            5'd18: block_data[9] = 64'hBE9AA086BF740BDD;
            5'd19: block_data[9] = 64'hBE9D9E78BF73913F;
            5'd20: block_data[9] = 64'hBEA09AE5BF731447;
            5'd21: block_data[9] = 64'hBEA395C5BF7294F8;
            5'd22: block_data[9] = 64'hBEA68F12BF721352;
            5'd23: block_data[9] = 64'hBEA986C4BF718F57;
            5'd24: block_data[9] = 64'hBEAC7CD4BF710908;
            5'd25: block_data[9] = 64'hBEAF713ABF708066;
            5'd26: block_data[9] = 64'hBEB263EFBF6FF573;
            5'd27: block_data[9] = 64'hBEB554ECBF6F6830;
            5'd28: block_data[9] = 64'hBEB8442ABF6ED89E;
            5'd29: block_data[9] = 64'hBEBB31A0BF6E46BE;
            5'd30: block_data[9] = 64'hBEBE1D4ABF6DB293;
            5'd31: block_data[9] = 64'hBEC1071EBF6D1C1D;
            default: block_data[9] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[10] = 64'hBEC3EF15BF6C835E;
            5'd1: block_data[10] = 64'hBEC6D529BF6BE858;
            5'd2: block_data[10] = 64'hBEC9B953BF6B4B0C;
            5'd3: block_data[10] = 64'hBECC9B8BBF6AAB7B;
            5'd4: block_data[10] = 64'hBECF7BCABF6A09A7;
            5'd5: block_data[10] = 64'hBED25A09BF696591;
            5'd6: block_data[10] = 64'hBED53641BF68BF3C;
            5'd7: block_data[10] = 64'hBED8106BBF6816A8;
            5'd8: block_data[10] = 64'hBEDAE880BF676BD8;
            5'd9: block_data[10] = 64'hBEDDBE79BF66BECC;
            5'd10: block_data[10] = 64'hBEE0924FBF660F88;
            5'd11: block_data[10] = 64'hBEE363FABF655E0B;
            5'd12: block_data[10] = 64'hBEE63375BF64AA59;
            5'd13: block_data[10] = 64'hBEE900B7BF63F473;
            5'd14: block_data[10] = 64'hBEEBCBBBBF633C5A;
            5'd15: block_data[10] = 64'hBEEE9479BF628210;
            5'd16: block_data[10] = 64'hBEF15AEABF61C598;
            5'd17: block_data[10] = 64'hBEF41F07BF6106F2;
            5'd18: block_data[10] = 64'hBEF6E0CBBF604621;
            5'd19: block_data[10] = 64'hBEF9A02DBF5F8327;
            5'd20: block_data[10] = 64'hBEFC5D27BF5EBE05;
            5'd21: block_data[10] = 64'hBEFF17B2BF5DF6BE;
            5'd22: block_data[10] = 64'hBF00E7E4BF5D2D53;
            5'd23: block_data[10] = 64'hBF0242B1BF5C61C7;
            5'd24: block_data[10] = 64'hBF039C3DBF5B941A;
            5'd25: block_data[10] = 64'hBF04F484BF5AC450;
            5'd26: block_data[10] = 64'hBF064B82BF59F26A;
            5'd27: block_data[10] = 64'hBF07A136BF591E6A;
            5'd28: block_data[10] = 64'hBF08F59BBF584853;
            5'd29: block_data[10] = 64'hBF0A48ADBF577026;
            5'd30: block_data[10] = 64'hBF0B9A6BBF5695E5;
            5'd31: block_data[10] = 64'hBF0CEAD0BF55B993;
            default: block_data[10] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[11] = 64'hBF0E39DABF54DB31;
            5'd1: block_data[11] = 64'hBF0F8784BF53FAC3;
            5'd2: block_data[11] = 64'hBF10D3CDBF531849;
            5'd3: block_data[11] = 64'hBF121EB0BF5233C6;
            5'd4: block_data[11] = 64'hBF13682ABF514D3D;
            5'd5: block_data[11] = 64'hBF14B039BF5064AF;
            5'd6: block_data[11] = 64'hBF15F6D9BF4F7A1F;
            5'd7: block_data[11] = 64'hBF173C07BF4E8D90;
            5'd8: block_data[11] = 64'hBF187FC0BF4D9F02;
            5'd9: block_data[11] = 64'hBF19C200BF4CAE79;
            5'd10: block_data[11] = 64'hBF1B02C6BF4BBBF8;
            5'd11: block_data[11] = 64'hBF1C420CBF4AC77F;
            5'd12: block_data[11] = 64'hBF1D7FD1BF49D112;
            5'd13: block_data[11] = 64'hBF1EBC12BF48D8B3;
            5'd14: block_data[11] = 64'hBF1FF6CBBF47DE65;
            5'd15: block_data[11] = 64'hBF212FF9BF46E22A;
            5'd16: block_data[11] = 64'hBF226799BF45E403;
            5'd17: block_data[11] = 64'hBF239DA9BF44E3F5;
            5'd18: block_data[11] = 64'hBF24D225BF43E200;
            5'd19: block_data[11] = 64'hBF26050ABF42DE29;
            5'd20: block_data[11] = 64'hBF273656BF41D870;
            5'd21: block_data[11] = 64'hBF286605BF40D0DA;
            5'd22: block_data[11] = 64'hBF299415BF3FC767;
            5'd23: block_data[11] = 64'hBF2AC082BF3EBC1B;
            5'd24: block_data[11] = 64'hBF2BEB4ABF3DAEF9;
            5'd25: block_data[11] = 64'hBF2D1469BF3CA003;
            5'd26: block_data[11] = 64'hBF2E3BDEBF3B8F3B;
            5'd27: block_data[11] = 64'hBF2F61A5BF3A7CA4;
            5'd28: block_data[11] = 64'hBF3085BBBF396842;
            5'd29: block_data[11] = 64'hBF31A81DBF385216;
            5'd30: block_data[11] = 64'hBF32C8C9BF373A23;
            5'd31: block_data[11] = 64'hBF33E7BCBF36206C;
            default: block_data[11] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[12] = 64'hBF3504F3BF3504F3;
            5'd1: block_data[12] = 64'hBF36206CBF33E7BC;
            5'd2: block_data[12] = 64'hBF373A23BF32C8C9;
            5'd3: block_data[12] = 64'hBF385216BF31A81D;
            5'd4: block_data[12] = 64'hBF396842BF3085BB;
            5'd5: block_data[12] = 64'hBF3A7CA4BF2F61A5;
            5'd6: block_data[12] = 64'hBF3B8F3BBF2E3BDE;
            5'd7: block_data[12] = 64'hBF3CA003BF2D1469;
            5'd8: block_data[12] = 64'hBF3DAEF9BF2BEB4A;
            5'd9: block_data[12] = 64'hBF3EBC1BBF2AC082;
            5'd10: block_data[12] = 64'hBF3FC767BF299415;
            5'd11: block_data[12] = 64'hBF40D0DABF286605;
            5'd12: block_data[12] = 64'hBF41D870BF273656;
            5'd13: block_data[12] = 64'hBF42DE29BF26050A;
            5'd14: block_data[12] = 64'hBF43E200BF24D225;
            5'd15: block_data[12] = 64'hBF44E3F5BF239DA9;
            5'd16: block_data[12] = 64'hBF45E403BF226799;
            5'd17: block_data[12] = 64'hBF46E22ABF212FF9;
            5'd18: block_data[12] = 64'hBF47DE65BF1FF6CB;
            5'd19: block_data[12] = 64'hBF48D8B3BF1EBC12;
            5'd20: block_data[12] = 64'hBF49D112BF1D7FD1;
            5'd21: block_data[12] = 64'hBF4AC77FBF1C420C;
            5'd22: block_data[12] = 64'hBF4BBBF8BF1B02C6;
            5'd23: block_data[12] = 64'hBF4CAE79BF19C200;
            5'd24: block_data[12] = 64'hBF4D9F02BF187FC0;
            5'd25: block_data[12] = 64'hBF4E8D90BF173C07;
            5'd26: block_data[12] = 64'hBF4F7A1FBF15F6D9;
            5'd27: block_data[12] = 64'hBF5064AFBF14B039;
            5'd28: block_data[12] = 64'hBF514D3DBF13682A;
            5'd29: block_data[12] = 64'hBF5233C6BF121EB0;
            5'd30: block_data[12] = 64'hBF531849BF10D3CD;
            5'd31: block_data[12] = 64'hBF53FAC3BF0F8784;
            default: block_data[12] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[13] = 64'hBF54DB31BF0E39DA;
            5'd1: block_data[13] = 64'hBF55B993BF0CEAD0;
            5'd2: block_data[13] = 64'hBF5695E5BF0B9A6B;
            5'd3: block_data[13] = 64'hBF577026BF0A48AD;
            5'd4: block_data[13] = 64'hBF584853BF08F59B;
            5'd5: block_data[13] = 64'hBF591E6ABF07A136;
            5'd6: block_data[13] = 64'hBF59F26ABF064B82;
            5'd7: block_data[13] = 64'hBF5AC450BF04F484;
            5'd8: block_data[13] = 64'hBF5B941ABF039C3D;
            5'd9: block_data[13] = 64'hBF5C61C7BF0242B1;
            5'd10: block_data[13] = 64'hBF5D2D53BF00E7E4;
            5'd11: block_data[13] = 64'hBF5DF6BEBEFF17B2;
            5'd12: block_data[13] = 64'hBF5EBE05BEFC5D27;
            5'd13: block_data[13] = 64'hBF5F8327BEF9A02D;
            5'd14: block_data[13] = 64'hBF604621BEF6E0CB;
            5'd15: block_data[13] = 64'hBF6106F2BEF41F07;
            5'd16: block_data[13] = 64'hBF61C598BEF15AEA;
            5'd17: block_data[13] = 64'hBF628210BEEE9479;
            5'd18: block_data[13] = 64'hBF633C5ABEEBCBBB;
            5'd19: block_data[13] = 64'hBF63F473BEE900B7;
            5'd20: block_data[13] = 64'hBF64AA59BEE63375;
            5'd21: block_data[13] = 64'hBF655E0BBEE363FA;
            5'd22: block_data[13] = 64'hBF660F88BEE0924F;
            5'd23: block_data[13] = 64'hBF66BECCBEDDBE79;
            5'd24: block_data[13] = 64'hBF676BD8BEDAE880;
            5'd25: block_data[13] = 64'hBF6816A8BED8106B;
            5'd26: block_data[13] = 64'hBF68BF3CBED53641;
            5'd27: block_data[13] = 64'hBF696591BED25A09;
            5'd28: block_data[13] = 64'hBF6A09A7BECF7BCA;
            5'd29: block_data[13] = 64'hBF6AAB7BBECC9B8B;
            5'd30: block_data[13] = 64'hBF6B4B0CBEC9B953;
            5'd31: block_data[13] = 64'hBF6BE858BEC6D529;
            default: block_data[13] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[14] = 64'hBF6C835EBEC3EF15;
            5'd1: block_data[14] = 64'hBF6D1C1DBEC1071E;
            5'd2: block_data[14] = 64'hBF6DB293BEBE1D4A;
            5'd3: block_data[14] = 64'hBF6E46BEBEBB31A0;
            5'd4: block_data[14] = 64'hBF6ED89EBEB8442A;
            5'd5: block_data[14] = 64'hBF6F6830BEB554EC;
            5'd6: block_data[14] = 64'hBF6FF573BEB263EF;
            5'd7: block_data[14] = 64'hBF708066BEAF713A;
            5'd8: block_data[14] = 64'hBF710908BEAC7CD4;
            5'd9: block_data[14] = 64'hBF718F57BEA986C4;
            5'd10: block_data[14] = 64'hBF721352BEA68F12;
            5'd11: block_data[14] = 64'hBF7294F8BEA395C5;
            5'd12: block_data[14] = 64'hBF731447BEA09AE5;
            5'd13: block_data[14] = 64'hBF73913FBE9D9E78;
            5'd14: block_data[14] = 64'hBF740BDDBE9AA086;
            5'd15: block_data[14] = 64'hBF748422BE97A117;
            5'd16: block_data[14] = 64'hBF74FA0BBE94A031;
            5'd17: block_data[14] = 64'hBF756D97BE919DDD;
            5'd18: block_data[14] = 64'hBF75DEC6BE8E9A22;
            5'd19: block_data[14] = 64'hBF764D97BE8B9507;
            5'd20: block_data[14] = 64'hBF76BA07BE888E93;
            5'd21: block_data[14] = 64'hBF772417BE8586CE;
            5'd22: block_data[14] = 64'hBF778BC5BE827DC0;
            5'd23: block_data[14] = 64'hBF77F110BE7EE6E1;
            5'd24: block_data[14] = 64'hBF7853F8BE78CFCC;
            5'd25: block_data[14] = 64'hBF78B47BBE72B651;
            5'd26: block_data[14] = 64'hBF791298BE6C9A7F;
            5'd27: block_data[14] = 64'hBF796E4EBE667C66;
            5'd28: block_data[14] = 64'hBF79C79DBE605C13;
            5'd29: block_data[14] = 64'hBF7A1E84BE5A3997;
            5'd30: block_data[14] = 64'hBF7A7302BE541501;
            5'd31: block_data[14] = 64'hBF7AC516BE4DEE60;
            default: block_data[14] = 64'h0000000000000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[15] = 64'hBF7B14BEBE47C5C2;
            5'd1: block_data[15] = 64'hBF7B61FCBE419B37;
            5'd2: block_data[15] = 64'hBF7BACCDBE3B6ECF;
            5'd3: block_data[15] = 64'hBF7BF531BE354098;
            5'd4: block_data[15] = 64'hBF7C3B28BE2F10A2;
            5'd5: block_data[15] = 64'hBF7C7EB0BE28DEFC;
            5'd6: block_data[15] = 64'hBF7CBFC9BE22ABB6;
            5'd7: block_data[15] = 64'hBF7CFE73BE1C76DE;
            5'd8: block_data[15] = 64'hBF7D3AACBE164083;
            5'd9: block_data[15] = 64'hBF7D7474BE1008B7;
            5'd10: block_data[15] = 64'hBF7DABCCBE09CF86;
            5'd11: block_data[15] = 64'hBF7DE0B1BE039502;
            5'd12: block_data[15] = 64'hBF7E1324BDFAB273;
            5'd13: block_data[15] = 64'hBF7E4323BDEE3876;
            5'd14: block_data[15] = 64'hBF7E70B0BDE1BC2E;
            5'd15: block_data[15] = 64'hBF7E9BC9BDD53DB9;
            5'd16: block_data[15] = 64'hBF7EC46DBDC8BD36;
            5'd17: block_data[15] = 64'hBF7EEA9DBDBC3AC3;
            5'd18: block_data[15] = 64'hBF7F0E58BDAFB680;
            5'd19: block_data[15] = 64'hBF7F2F9DBDA3308C;
            5'd20: block_data[15] = 64'hBF7F4E6DBD96A905;
            5'd21: block_data[15] = 64'hBF7F6AC7BD8A200A;
            5'd22: block_data[15] = 64'hBF7F84ABBD7B2B74;
            5'd23: block_data[15] = 64'hBF7F9C18BD621469;
            5'd24: block_data[15] = 64'hBF7FB10FBD48FB30;
            5'd25: block_data[15] = 64'hBF7FC38FBD2FE007;
            5'd26: block_data[15] = 64'hBF7FD397BD16C32C;
            5'd27: block_data[15] = 64'hBF7FE129BCFB49BA;
            5'd28: block_data[15] = 64'hBF7FEC43BCC90AB0;
            5'd29: block_data[15] = 64'hBF7FF4E6BC96C9B6;
            5'd30: block_data[15] = 64'hBF7FFB11BC490E90;
            5'd31: block_data[15] = 64'hBF7FFEC4BBC90F88;
            default: block_data[15] = 64'h0000000000000000;
        endcase
    end

    reg [63:0] raw_data;

    always @(*) begin
        raw_data = block_data[rom_addr[8:5]];
    end

    // --------------------------------------------------------
    // 4. Output Generation
    // --------------------------------------------------------
    always @(*) begin
        if (is_midpoint) begin
            // Hardcoded -1.0 (real = -1.0 -> 0xBF800000, imag = +0.0 -> 0x00000000)
            twiddle_out = 64'hBF80_0000_0000_0000;
        end else begin
            twiddle_out = raw_data;

            // Apply conjugate (flip the sign of the imaginary part)
            if (use_conjugate) begin
                if (twiddle_out[31:0] != 32'h0000_0000)
                    twiddle_out[31:0] = {~twiddle_out[31], twiddle_out[30:0]};
            end
        end
    end

endmodule
