#!/usr/bin/env python3
"""
soc_firmware_gen.py
====================
Parametrized replacement for the hand-written fft_batch_test.asm (which was
fixed at N=256, 11 tests, 1 word/sample). Builds the same program shape --
for each of NUM_TESTS signals: load N samples, fftstart, fftwait with a
timeout counter, store N results -- for any (N, transfer_mode) pair.

transfer_mode:
  "single" -- one fftload/fftstore per sample (mixed FP4/FP8, FP16: both fit
              in one 32-bit word; see soc_wrapper_gen.py).
  "hilo64" -- two instructions per sample on both ends (fftload+fftloadhi,
              fftstore+fftstorehi; FP32 only -- 64-bit samples, see
              soc_wrapper_gen.py's generate_hilo64_wrapper).

Memory layout is computed here (not fixed at the old 2048/5120-word
offsets), because FP32 at N=1024 needs 11*1024*2 = 22528 words just for the
inputs -- more than fits before word 5120. Returns a MemLayout the caller
feeds both into the assembly (as base addresses) and into tb_fft_soc_perf.v
(as -D overrides), so the two stay consistent by construction.
"""
from dataclasses import dataclass


@dataclass
class MemLayout:
    words_per_sample: int        # 1 (single) or 2 (hilo64)
    store_pad_ops: int           # extra dummy store ops appended per frame
    timeout_counter_word: int
    samples_base_word: int
    results_base_word: int
    mem_words: int


def compute_layout(n, num_tests, transfer_mode):
    words_per_sample = 1 if transfer_mode == "single" else 2
    # tb_fft_soc_perf.v's `finished` (and its dump) fires 4 cycles after the
    # LAST counted store op completes. For every store except the very last
    # one in the whole run that's irrelevant (the sim keeps going
    # regardless); for the LAST one, the firmware's own trailing `sw`
    # (committing that PCPI op's result to memory) races the same 4-cycle
    # window. Confirmed losing that race in practice for BOTH transfer
    # modes at small N (observed on mixed and fp16 at N=2, not just
    # hilo64/FP32) -- the margin depends on exact pipeline timing, not
    # something to assume away for configs not yet tried. Two harmless
    # dummy store ops per frame (result discarded, no `sw`) push
    # `finished`'s trigger comfortably past the real data's commit.
    store_pad_ops = 2
    sample_data_words = num_tests * n * words_per_sample
    # The padding ops never touch s2/sw -- results stay DENSELY packed (no
    # per-frame gap); padding only delays when tb_fft_soc_perf.v's dump
    # fires, not where real data lands. dump_results() itself reads
    # FFT_N*NUM_TESTS words regardless (more than was actually written when
    # store_pad_ops>0), so mem_words needs room for that overread too.
    result_data_words = num_tests * n * words_per_sample
    result_dump_words = num_tests * (n * words_per_sample + store_pad_ops)
    timeout_counter_word = 256          # program is a few dozen words; ample room
    samples_base_word = 512
    results_base_word = samples_base_word + sample_data_words
    mem_words = results_base_word + max(result_data_words, result_dump_words) + 64
    return MemLayout(words_per_sample, store_pad_ops, timeout_counter_word,
                      samples_base_word, results_base_word, mem_words)


def build_asm_lines(n, num_tests, transfer_mode, layout, fftwait_timeout=None):
    """Returns the program as a list of text lines, assemble()-ready."""
    if fftwait_timeout is None:
        # Generous: load+compute+unload for N samples, scaled from the
        # original 8000-cycle budget at N=256 with headroom.
        fftwait_timeout = max(8000, 40 * n)

    samples_byte = layout.samples_base_word * 4
    results_byte = layout.results_base_word * 4
    timeout_byte = layout.timeout_counter_word * 4

    lines = [
        f"# Auto-generated by soc_firmware_gen.py: N={n} tests={num_tests} "
        f"mode={transfer_mode}",
        "_start:",
        f"    li   s11, {num_tests}        # number of test signals",
        "    li   s10, 0              # current test index",
        f"    li   s1, {samples_byte}       # SAMPLES_BASE address",
        f"    li   s2, {results_byte}       # RESULTS_BASE address",
        f"    li   s4, {timeout_byte}       # TIMEOUT_COUNTER address",
        "    li   t2, 0",
        "    sw   t2, 0(s4)            # clear timeout counter",
        "",
        "outer_loop:",
        "    bge  s10, s11, halt      # if test index >= num_tests, done",
        "",
        "    # 1. Load N samples into accelerator",
        "    li   s0, 0               # i = 0",
        f"    li   t1, {n}",
        "loop_load:",
    ]

    if transfer_mode == "single":
        lines += [
            "    lw   t0, 0(s1)",
            "    fftload x0, t0, s0",
            "    addi s1, s1, 4",
        ]
    else:
        lines += [
            "    lw   t0, 0(s1)",
            "    fftload x0, t0, s0",
            "    lw   t0, 4(s1)",
            "    fftloadhi x0, t0, s0",
            "    addi s1, s1, 8",
        ]

    lines += [
        "    addi s0, s0, 1",
        "    blt  s0, t1, loop_load",
        "",
        "    # 2. Fire FFT and wait",
        "    fftstart",
        f"    li   a1, {fftwait_timeout}",
        "    fftwait a0, a1",
        "    bne  a0, x0, no_timeout   # a0==1 -> done in time, skip",
        "    lw   t2, 0(s4)",
        "    addi t2, t2, 1",
        "    sw   t2, 0(s4)            # a0==0 -> timed out, bump the counter",
        "no_timeout:",
        "",
        "    # 3. Store N results to memory",
        "    li   s0, 0",
        "loop_store:",
    ]

    if transfer_mode == "single":
        lines += [
            "    fftstore t0, s0",
            "    sw   t0, 0(s2)",
            "    addi s2, s2, 4",
        ]
    else:
        lines += [
            "    fftstore t0, s0",
            "    sw   t0, 0(s2)",
            "    fftstorehi t0, s0",
            "    sw   t0, 4(s2)",
            "    addi s2, s2, 8",
        ]

    lines += [
        "    addi s0, s0, 1",
        "    blt  s0, t1, loop_store",
    ]

    if layout.store_pad_ops:
        assert layout.store_pad_ops == 2
        lines += [
            "",
            "    # Padding: see MemLayout.store_pad_ops -- result discarded,",
            "    # no sw, purely to push tb_fft_soc_perf.v's finished-trigger",
            "    # past the real last store's own sw.",
        ]
        if transfer_mode == "single":
            lines += ["    fftstore t3, s0", "    fftstore t3, s0"]
        else:
            lines += ["    fftstore t3, s0", "    fftstorehi t3, s0"]

    lines += [
        "",
        "    # Increment test counter and repeat",
        "    addi s10, s10, 1",
        "    j    outer_loop",
        "",
        "halt:",
        "    j halt",
    ]
    return lines
