#!/usr/bin/env python3
"""
soc_wrapper_gen.py
===================
Generates fft_pcpi_wrapper.v for a given (top-module, address-width,
data-width) combination, instead of the single hardcoded
(mixed_fft_256_top, 8-bit addr, 16-bit data) copy that used to be checked
in as fft_pcpi_wrapper.v / written by soc_evaluator.py's
generate_bulletproof_wrapper().

Two protocol shapes, picked by width:
  * single-register (<=32-bit samples): mixed FP4/FP8 (16-bit, every N) and
    FP16 (32-bit, every N). One FFTLOAD/FFTSTORE per sample, same 5-state
    handshake as the original hardcoded wrapper -- this function with
    data_width=16 and addr_width=8 reproduces that file byte-for-byte
    (checked by the self-test at the bottom).
  * hi/lo (64-bit samples): FP32 only. A 64-bit complex sample doesn't fit
    one RV32 register, so two new custom-0 ops are added (funct3 110
    FFTLOADHI, 111 FFTSTOREHI -- both free in the existing 3-bit space; see
    encode_insn.py). FFTLOAD now only stages the low (real) word into a
    register; FFTLOADHI supplies the high (imag) word and is the one that
    actually pulses the FFT core's load_en with the combined 64-bit word
    (mirrors the original single-pulse-on-state==0 pattern exactly, just
    gated on f3==110 instead of f3==001). FFTSTORE and FFTSTOREHI each
    independently re-run the full unload_en pipeline hold against the same
    address and capture the low/high half respectively -- simpler and
    lower-risk than latching the pipelined read once and splitting it, at
    the cost of one extra pipeline wait per sample on store.
"""
import math


def _addr_width(n):
    return max(1, math.ceil(math.log2(n)))


def generate_single_register_wrapper(top_module, addr_width, data_width):
    """data_width in {16, 32}. load_data/unload_data on the FFT core are
    exactly data_width bits; the whole sample fits in one pcpi_rs1/pcpi_rd."""
    assert data_width in (16, 32)
    pad = 32 - data_width
    rd_assign = ("pcpi_rd <= fft_unload_data;" if pad == 0 else
                 f"pcpi_rd <= {{{pad}'b0, fft_unload_data}};")
    return f"""`timescale 1ns/1ps
// Generated by soc_wrapper_gen.py -- DO NOT hand-edit.
// top={top_module} addr_width={addr_width} data_width={data_width}
module fft_pcpi_wrapper (
    input clk, input rst_n, input pcpi_valid, input [31:0] pcpi_insn,
    input [31:0] pcpi_rs1, input [31:0] pcpi_rs2,
    output reg pcpi_wr, output reg [31:0] pcpi_rd, output reg pcpi_wait, output reg pcpi_ready
);
    wire is_custom0 = pcpi_valid && (pcpi_insn[6:0] == 7'b0001011);
    wire [2:0] f3 = pcpi_insn[14:12];

    reg [2:0] state;

    // 1-cycle pulses for load and start
    wire fft_load_en = is_custom0 && (f3 == 3'b001) && (state == 0) && !pcpi_ready;
    wire fft_start   = is_custom0 && (f3 == 3'b011) && (state == 0) && !pcpi_ready;

    // Multi-cycle hold for SRAM pipeline reads
    wire fft_unload_en = is_custom0 && (f3 == 3'b010) && !pcpi_ready;

    wire fft_done;
    wire [{data_width - 1}:0] fft_unload_data;

    {top_module} u_fft (
        .clk(clk), .rst(rst_n), .start(fft_start), .done(fft_done),
        .load_en(fft_load_en), .load_addr(pcpi_rs2[{addr_width - 1}:0]), .load_data(pcpi_rs1[{data_width - 1}:0]),
        .unload_en(fft_unload_en), .unload_addr(pcpi_rs1[{addr_width - 1}:0]), .unload_data(fft_unload_data)
    );

    reg status_done;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) status_done <= 0;
        else if (fft_start) status_done <= 0;
        else if (fft_done) status_done <= 1;
    end

    reg [31:0] timeout;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= 0; pcpi_ready <= 0; pcpi_wr <= 0; pcpi_rd <= 0; pcpi_wait <= 0;
        end else begin
            pcpi_ready <= 0; pcpi_wr <= 0; pcpi_wait <= 0;
            if (is_custom0 && !pcpi_ready) begin
                pcpi_wait <= 1;
                if (f3 == 3'b001 || f3 == 3'b010 || f3 == 3'b011) begin
                    if (state == 4) begin
                        pcpi_ready <= 1; pcpi_wait <= 0; state <= 0;
                        if (f3 == 3'b010) begin
                            pcpi_wr <= 1; {rd_assign}
                        end
                    end else begin
                        state <= state + 1;
                    end
                end else if (f3 == 3'b100) begin
                    if (state == 0) begin
                        timeout <= pcpi_rs1; state <= 1;
                    end else begin
                        if (status_done) begin
                            pcpi_ready <= 1; pcpi_wr <= 1; pcpi_rd <= 1; pcpi_wait <= 0; state <= 0;
                        end else if (timeout == 1) begin
                            pcpi_ready <= 1; pcpi_wr <= 1; pcpi_rd <= 0; pcpi_wait <= 0; state <= 0;
                        end else timeout <= timeout - 1;
                    end
                end else if (f3 == 3'b101) begin
                    pcpi_ready <= 1; pcpi_wr <= 1; pcpi_rd <= {{31'b0, status_done}}; pcpi_wait <= 0;
                end
            end
        end
    end
endmodule
"""


def generate_hilo64_wrapper(top_module, addr_width):
    """FP32 only: 64-bit samples via two instructions each for load/store."""
    return f"""`timescale 1ns/1ps
// Generated by soc_wrapper_gen.py -- DO NOT hand-edit.
// top={top_module} addr_width={addr_width} data_width=64 (hi/lo protocol)
module fft_pcpi_wrapper (
    input clk, input rst_n, input pcpi_valid, input [31:0] pcpi_insn,
    input [31:0] pcpi_rs1, input [31:0] pcpi_rs2,
    output reg pcpi_wr, output reg [31:0] pcpi_rd, output reg pcpi_wait, output reg pcpi_ready
);
    wire is_custom0 = pcpi_valid && (pcpi_insn[6:0] == 7'b0001011);
    wire [2:0] f3 = pcpi_insn[14:12];
    // funct7==1 marks the HIGH (imag on load, real on store) half; see
    // encode_insn.py's module docstring for why this reuses FFTLOAD's/
    // FFTSTORE's own funct3 instead of new funct3 codes.
    wire is_hi = pcpi_insn[25];

    reg [2:0] state;

    // FFTLOAD lo (funct7=0) only stages the low/imag word -- no FFT core
    // access. FFTLOAD hi (funct7=1) supplies the high/real word and is the
    // one that actually pulses the FFT core's load_en, mirroring the
    // original single-pulse-on-state==0 shape.
    wire fft_load_lo_en = is_custom0 && (f3 == 3'b001) && !is_hi && (state == 0) && !pcpi_ready;
    wire fft_load_en    = is_custom0 && (f3 == 3'b001) &&  is_hi && (state == 0) && !pcpi_ready;
    wire fft_start      = is_custom0 && (f3 == 3'b011) && (state == 0) && !pcpi_ready;

    // FFTSTORE lo and hi (both funct3=010) each independently hold
    // unload_en across the full pipeline latency against the same address
    // and capture their own half at state==4.
    wire fft_unload_en = is_custom0 && (f3 == 3'b010) && !pcpi_ready;

    reg [31:0] stage_lo;   // imag/low word latched by FFTLOAD lo, consumed by FFTLOAD hi

    always @(posedge clk) begin
        if (fft_load_lo_en) stage_lo <= pcpi_rs1;
    end

    wire fft_done;
    wire [63:0] fft_unload_data;

    {top_module} u_fft (
        .clk(clk), .rst(rst_n), .start(fft_start), .done(fft_done),
        .load_en(fft_load_en), .load_addr(pcpi_rs2[{addr_width - 1}:0]), .load_data({{pcpi_rs1, stage_lo}}),
        .unload_en(fft_unload_en), .unload_addr(pcpi_rs1[{addr_width - 1}:0]), .unload_data(fft_unload_data)
    );

    reg status_done;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) status_done <= 0;
        else if (fft_start) status_done <= 0;
        else if (fft_done) status_done <= 1;
    end

    reg [31:0] timeout;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= 0; pcpi_ready <= 0; pcpi_wr <= 0; pcpi_rd <= 0; pcpi_wait <= 0;
        end else begin
            pcpi_ready <= 0; pcpi_wr <= 0; pcpi_wait <= 0;
            if (is_custom0 && !pcpi_ready) begin
                pcpi_wait <= 1;
                if (f3 == 3'b001 || f3 == 3'b010 || f3 == 3'b011) begin
                    if (state == 4) begin
                        pcpi_ready <= 1; pcpi_wait <= 0; state <= 0;
                        if (f3 == 3'b010) begin
                            pcpi_wr <= 1;
                            if (is_hi) pcpi_rd <= fft_unload_data[63:32];
                            else       pcpi_rd <= fft_unload_data[31:0];
                        end
                    end else begin
                        state <= state + 1;
                    end
                end else if (f3 == 3'b100) begin
                    if (state == 0) begin
                        timeout <= pcpi_rs1; state <= 1;
                    end else begin
                        if (status_done) begin
                            pcpi_ready <= 1; pcpi_wr <= 1; pcpi_rd <= 1; pcpi_wait <= 0; state <= 0;
                        end else if (timeout == 1) begin
                            pcpi_ready <= 1; pcpi_wr <= 1; pcpi_rd <= 0; pcpi_wait <= 0; state <= 0;
                        end else timeout <= timeout - 1;
                    end
                end else if (f3 == 3'b101) begin
                    pcpi_ready <= 1; pcpi_wr <= 1; pcpi_rd <= {{31'b0, status_done}}; pcpi_wait <= 0;
                end
            end
        end
    end
endmodule
"""


def generate_wrapper(top_module, n, data_width):
    """data_width in {16, 32, 64}. Returns Verilog source text."""
    addr_width = _addr_width(n)
    if data_width in (16, 32):
        return generate_single_register_wrapper(top_module, addr_width, data_width)
    elif data_width == 64:
        return generate_hilo64_wrapper(top_module, addr_width)
    raise ValueError(f"unsupported data_width {data_width}")


if __name__ == "__main__":
    # Self-test: addr_width=8, data_width=16, top=mixed_fft_256_top must
    # reproduce the original hand-written fft_pcpi_wrapper.v (module body,
    # modulo the removed diagnostic $display block and the header comment).
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    generated = generate_single_register_wrapper("mixed_fft_256_top", 8, 16)
    print(generated)
