// =============================================================================
// FP16 Twiddle Factor ROM -- synthesizable case-statement version
// =============================================================================
// AUTO-GENERATED by generate_fp16_twiddles.py -- do not hand-edit the ROM
// table below; re-run the generator instead.
//
// Mirrors twiddle_factor_fp32 in fp32_baseline/source/fp32_twiddle_rom.v:
// same dynamic k-scaling for runtime N, same half-plane symmetry +
// conjugation, same hardcoded -1.0 midpoint. The stored word is 32-bit
// complex FP16 instead of 64-bit complex FP32, and there is no PRECISION
// port.
//
// ROM word format: [31:16] FP16 Real, [15:0] FP16 Imag
//
// All 512 entries are sourced directly from twiddles_fp16_1024.txt
// (authoritative) via generate_fp16_twiddles.py. Yosys/OpenROAD infer this
// as a ROM mapped to library cells -- no external file dependency at
// synthesis time, no working-directory-relative path to get wrong.
//
// Conjugate symmetry: only k=0..511 are stored.
//   W_N^{N-k} = conj(W_N^k) -> second half handled by flipping the
//   imaginary sign bit. k=512 (W=-1+0j) is hardcoded separately.
//
// Internally 1-cycle pipelined at the address/lookup boundary (register
// between "2. Symmetry Logic" and "3. ROM"): a single flat 512-way
// case statement measured on a real post-route netlist as a ~40-gate-deep
// combinational chain (not the balanced ~log2(512)-level tree a
// well-structured mux would give -- Yosys/ABC do not automatically balance
// one huge flat case with fully arbitrary constants and no sharing
// opportunity). The lookup below is therefore written as an explicit
// 16-way outer selection over 16 independent
// 32-way inner blocks (rom_addr[8:5]
// picks the block, rom_addr[4:0] picks within it), still
// fully combinational and still inside the same single post-register cycle
// -- this just gives the synthesis tool a hierarchy to map onto instead of
// one flat 512-way structure, bounding each stage's depth to a
// 32-way / 16-way mux. The caller must add 1
// matching cycle to its alignment pipeline for the address/lookup register
// -- see TWIDDLE_LATENCY in fp16_template_generator.py.
// =============================================================================

module twiddle_factor_fp16 #(
    parameter MAX_N      = 1024,
    parameter ADDR_WIDTH = $clog2(MAX_N) + 1
)(
    input                    clk,
    input  [ADDR_WIDTH-1:0] k,            // Index k
    input  [ADDR_WIDTH-1:0] n,            // Current FFT size N
    output reg [31:0]       twiddle_out
);

    // --------------------------------------------------------
    // 1. Dynamic Scaling Logic
    // --------------------------------------------------------
    reg [ADDR_WIDTH-1:0] scaled_k;

    always @(*) begin
        case (n)
            1024: scaled_k = k;
            512:  scaled_k = {k, 1'b0};         // k * 2
            256:  scaled_k = {k, 2'b00};        // k * 4
            128:  scaled_k = {k, 3'b000};       // k * 8
            64:   scaled_k = {k, 4'b0000};      // k * 16
            32:   scaled_k = {k, 5'b00000};     // k * 32
            16:   scaled_k = {k, 6'b000000};    // k * 64
            8:    scaled_k = {k, 7'b0000000};   // k * 128
            4:    scaled_k = {k, 8'b00000000};  // k * 256
            2:    scaled_k = {k, 9'b000000000}; // k * 512
            default: scaled_k = 11'd0;
        endcase
    end

    // --------------------------------------------------------
    // 2. Symmetry Logic
    // --------------------------------------------------------
    reg        use_conjugate_w;
    reg [9:0]  rom_addr_w;       // Address within the 0-511 block
    reg        is_midpoint_w;

    always @(*) begin
        is_midpoint_w = 1'b0;

        if (scaled_k == 512) begin
            // 180 degrees is a boundary case
            is_midpoint_w   = 1'b1;
            rom_addr_w      = 0;
            use_conjugate_w = 1'b0;
        end
        else if (scaled_k > 511) begin
            // Second half (180 < angle < 360) -> Symmetry
            rom_addr_w      = 1024 - scaled_k;
            use_conjugate_w = 1'b1;
        end
        else begin
            // First half (0 <= angle < 180)
            rom_addr_w      = scaled_k;
            use_conjugate_w = 1'b0;
        end
    end

    // ---- pipeline register: address computation | ROM lookup ----
    reg        use_conjugate;
    reg [9:0]  rom_addr;
    reg        is_midpoint;

    always @(posedge clk) begin
        use_conjugate <= use_conjugate_w;
        rom_addr      <= rom_addr_w;
        is_midpoint   <= is_midpoint_w;
    end

    // --------------------------------------------------------
    // 3. ROM -- 512 entries as 16 independent
    //    32-way combinational blocks, outer-selected by
    //    rom_addr[8:5]. See header comment for why.
    // --------------------------------------------------------
    reg [31:0] block_data [0:15];

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[0] = 32'h3C000000;
            5'd1: block_data[0] = 32'h3C009E48;
            5'd2: block_data[0] = 32'h3C00A248;
            5'd3: block_data[0] = 32'h3C00A4B6;
            5'd4: block_data[0] = 32'h3BFFA648;
            5'd5: block_data[0] = 32'h3BFFA7DA;
            5'd6: block_data[0] = 32'h3BFFA8B6;
            5'd7: block_data[0] = 32'h3BFEA97F;
            5'd8: block_data[0] = 32'h3BFEAA48;
            5'd9: block_data[0] = 32'h3BFDAB11;
            5'd10: block_data[0] = 32'h3BFCABD9;
            5'd11: block_data[0] = 32'h3BFBAC51;
            5'd12: block_data[0] = 32'h3BFAACB5;
            5'd13: block_data[0] = 32'h3BF9AD1A;
            5'd14: block_data[0] = 32'h3BF8AD7E;
            5'd15: block_data[0] = 32'h3BF7ADE2;
            5'd16: block_data[0] = 32'h3BF6AE46;
            5'd17: block_data[0] = 32'h3BF5AEAA;
            5'd18: block_data[0] = 32'h3BF4AF0E;
            5'd19: block_data[0] = 32'h3BF2AF72;
            5'd20: block_data[0] = 32'h3BF1AFD6;
            5'd21: block_data[0] = 32'h3BEFB01D;
            5'd22: block_data[0] = 32'h3BEDB04E;
            5'd23: block_data[0] = 32'h3BECB080;
            5'd24: block_data[0] = 32'h3BEAB0B2;
            5'd25: block_data[0] = 32'h3BE8B0E4;
            5'd26: block_data[0] = 32'h3BE6B115;
            5'd27: block_data[0] = 32'h3BE4B147;
            5'd28: block_data[0] = 32'h3BE2B179;
            5'd29: block_data[0] = 32'h3BE0B1AA;
            5'd30: block_data[0] = 32'h3BDDB1DB;
            5'd31: block_data[0] = 32'h3BDBB20D;
            default: block_data[0] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[1] = 32'h3BD9B23E;
            5'd1: block_data[1] = 32'h3BD6B26F;
            5'd2: block_data[1] = 32'h3BD4B2A1;
            5'd3: block_data[1] = 32'h3BD1B2D2;
            5'd4: block_data[1] = 32'h3BCEB303;
            5'd5: block_data[1] = 32'h3BCBB334;
            5'd6: block_data[1] = 32'h3BC9B365;
            5'd7: block_data[1] = 32'h3BC6B396;
            5'd8: block_data[1] = 32'h3BC3B3C6;
            5'd9: block_data[1] = 32'h3BC0B3F7;
            5'd10: block_data[1] = 32'h3BBCB414;
            5'd11: block_data[1] = 32'h3BB9B42C;
            5'd12: block_data[1] = 32'h3BB6B444;
            5'd13: block_data[1] = 32'h3BB2B45D;
            5'd14: block_data[1] = 32'h3BAFB475;
            5'd15: block_data[1] = 32'h3BABB48D;
            5'd16: block_data[1] = 32'h3BA8B4A5;
            5'd17: block_data[1] = 32'h3BA4B4BD;
            5'd18: block_data[1] = 32'h3BA0B4D5;
            5'd19: block_data[1] = 32'h3B9DB4ED;
            5'd20: block_data[1] = 32'h3B99B505;
            5'd21: block_data[1] = 32'h3B95B51D;
            5'd22: block_data[1] = 32'h3B91B534;
            5'd23: block_data[1] = 32'h3B8CB54C;
            5'd24: block_data[1] = 32'h3B88B564;
            5'd25: block_data[1] = 32'h3B84B57C;
            5'd26: block_data[1] = 32'h3B80B593;
            5'd27: block_data[1] = 32'h3B7BB5AB;
            5'd28: block_data[1] = 32'h3B77B5C2;
            5'd29: block_data[1] = 32'h3B72B5DA;
            5'd30: block_data[1] = 32'h3B6EB5F1;
            5'd31: block_data[1] = 32'h3B69B608;
            default: block_data[1] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[2] = 32'h3B64B61F;
            5'd1: block_data[2] = 32'h3B5FB637;
            5'd2: block_data[2] = 32'h3B5AB64E;
            5'd3: block_data[2] = 32'h3B55B665;
            5'd4: block_data[2] = 32'h3B50B67C;
            5'd5: block_data[2] = 32'h3B4BB693;
            5'd6: block_data[2] = 32'h3B46B6AA;
            5'd7: block_data[2] = 32'h3B41B6C1;
            5'd8: block_data[2] = 32'h3B3BB6D7;
            5'd9: block_data[2] = 32'h3B36B6EE;
            5'd10: block_data[2] = 32'h3B30B705;
            5'd11: block_data[2] = 32'h3B2BB71B;
            5'd12: block_data[2] = 32'h3B25B732;
            5'd13: block_data[2] = 32'h3B20B748;
            5'd14: block_data[2] = 32'h3B1AB75E;
            5'd15: block_data[2] = 32'h3B14B775;
            5'd16: block_data[2] = 32'h3B0EB78B;
            5'd17: block_data[2] = 32'h3B08B7A1;
            5'd18: block_data[2] = 32'h3B02B7B7;
            5'd19: block_data[2] = 32'h3AFCB7CD;
            5'd20: block_data[2] = 32'h3AF6B7E3;
            5'd21: block_data[2] = 32'h3AF0B7F9;
            5'd22: block_data[2] = 32'h3AE9B807;
            5'd23: block_data[2] = 32'h3AE3B812;
            5'd24: block_data[2] = 32'h3ADDB81D;
            5'd25: block_data[2] = 32'h3AD6B828;
            5'd26: block_data[2] = 32'h3AD0B832;
            5'd27: block_data[2] = 32'h3AC9B83D;
            5'd28: block_data[2] = 32'h3AC2B848;
            5'd29: block_data[2] = 32'h3ABCB852;
            5'd30: block_data[2] = 32'h3AB5B85D;
            5'd31: block_data[2] = 32'h3AAEB867;
            default: block_data[2] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[3] = 32'h3AA7B872;
            5'd1: block_data[3] = 32'h3AA0B87C;
            5'd2: block_data[3] = 32'h3A99B887;
            5'd3: block_data[3] = 32'h3A92B891;
            5'd4: block_data[3] = 32'h3A8AB89B;
            5'd5: block_data[3] = 32'h3A83B8A6;
            5'd6: block_data[3] = 32'h3A7CB8B0;
            5'd7: block_data[3] = 32'h3A74B8BA;
            5'd8: block_data[3] = 32'h3A6DB8C4;
            5'd9: block_data[3] = 32'h3A65B8CE;
            5'd10: block_data[3] = 32'h3A5EB8D8;
            5'd11: block_data[3] = 32'h3A56B8E2;
            5'd12: block_data[3] = 32'h3A4FB8EC;
            5'd13: block_data[3] = 32'h3A47B8F6;
            5'd14: block_data[3] = 32'h3A3FB900;
            5'd15: block_data[3] = 32'h3A37B909;
            5'd16: block_data[3] = 32'h3A2FB913;
            5'd17: block_data[3] = 32'h3A27B91D;
            5'd18: block_data[3] = 32'h3A1FB927;
            5'd19: block_data[3] = 32'h3A17B930;
            5'd20: block_data[3] = 32'h3A0FB93A;
            5'd21: block_data[3] = 32'h3A07B943;
            5'd22: block_data[3] = 32'h39FEB94D;
            5'd23: block_data[3] = 32'h39F6B956;
            5'd24: block_data[3] = 32'h39EDB95F;
            5'd25: block_data[3] = 32'h39E5B969;
            5'd26: block_data[3] = 32'h39DCB972;
            5'd27: block_data[3] = 32'h39D4B97B;
            5'd28: block_data[3] = 32'h39CBB984;
            5'd29: block_data[3] = 32'h39C3B98D;
            5'd30: block_data[3] = 32'h39BAB996;
            5'd31: block_data[3] = 32'h39B1B99F;
            default: block_data[3] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[4] = 32'h39A8B9A8;
            5'd1: block_data[4] = 32'h399FB9B1;
            5'd2: block_data[4] = 32'h3996B9BA;
            5'd3: block_data[4] = 32'h398DB9C3;
            5'd4: block_data[4] = 32'h3984B9CB;
            5'd5: block_data[4] = 32'h397BB9D4;
            5'd6: block_data[4] = 32'h3972B9DC;
            5'd7: block_data[4] = 32'h3969B9E5;
            5'd8: block_data[4] = 32'h395FB9ED;
            5'd9: block_data[4] = 32'h3956B9F6;
            5'd10: block_data[4] = 32'h394DB9FE;
            5'd11: block_data[4] = 32'h3943BA07;
            5'd12: block_data[4] = 32'h393ABA0F;
            5'd13: block_data[4] = 32'h3930BA17;
            5'd14: block_data[4] = 32'h3927BA1F;
            5'd15: block_data[4] = 32'h391DBA27;
            5'd16: block_data[4] = 32'h3913BA2F;
            5'd17: block_data[4] = 32'h3909BA37;
            5'd18: block_data[4] = 32'h3900BA3F;
            5'd19: block_data[4] = 32'h38F6BA47;
            5'd20: block_data[4] = 32'h38ECBA4F;
            5'd21: block_data[4] = 32'h38E2BA56;
            5'd22: block_data[4] = 32'h38D8BA5E;
            5'd23: block_data[4] = 32'h38CEBA65;
            5'd24: block_data[4] = 32'h38C4BA6D;
            5'd25: block_data[4] = 32'h38BABA74;
            5'd26: block_data[4] = 32'h38B0BA7C;
            5'd27: block_data[4] = 32'h38A6BA83;
            5'd28: block_data[4] = 32'h389BBA8A;
            5'd29: block_data[4] = 32'h3891BA92;
            5'd30: block_data[4] = 32'h3887BA99;
            5'd31: block_data[4] = 32'h387CBAA0;
            default: block_data[4] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[5] = 32'h3872BAA7;
            5'd1: block_data[5] = 32'h3867BAAE;
            5'd2: block_data[5] = 32'h385DBAB5;
            5'd3: block_data[5] = 32'h3852BABC;
            5'd4: block_data[5] = 32'h3848BAC2;
            5'd5: block_data[5] = 32'h383DBAC9;
            5'd6: block_data[5] = 32'h3832BAD0;
            5'd7: block_data[5] = 32'h3828BAD6;
            5'd8: block_data[5] = 32'h381DBADD;
            5'd9: block_data[5] = 32'h3812BAE3;
            5'd10: block_data[5] = 32'h3807BAE9;
            5'd11: block_data[5] = 32'h37F9BAF0;
            5'd12: block_data[5] = 32'h37E3BAF6;
            5'd13: block_data[5] = 32'h37CDBAFC;
            5'd14: block_data[5] = 32'h37B7BB02;
            5'd15: block_data[5] = 32'h37A1BB08;
            5'd16: block_data[5] = 32'h378BBB0E;
            5'd17: block_data[5] = 32'h3775BB14;
            5'd18: block_data[5] = 32'h375EBB1A;
            5'd19: block_data[5] = 32'h3748BB20;
            5'd20: block_data[5] = 32'h3732BB25;
            5'd21: block_data[5] = 32'h371BBB2B;
            5'd22: block_data[5] = 32'h3705BB30;
            5'd23: block_data[5] = 32'h36EEBB36;
            5'd24: block_data[5] = 32'h36D7BB3B;
            5'd25: block_data[5] = 32'h36C1BB41;
            5'd26: block_data[5] = 32'h36AABB46;
            5'd27: block_data[5] = 32'h3693BB4B;
            5'd28: block_data[5] = 32'h367CBB50;
            5'd29: block_data[5] = 32'h3665BB55;
            5'd30: block_data[5] = 32'h364EBB5A;
            5'd31: block_data[5] = 32'h3637BB5F;
            default: block_data[5] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[6] = 32'h361FBB64;
            5'd1: block_data[6] = 32'h3608BB69;
            5'd2: block_data[6] = 32'h35F1BB6E;
            5'd3: block_data[6] = 32'h35DABB72;
            5'd4: block_data[6] = 32'h35C2BB77;
            5'd5: block_data[6] = 32'h35ABBB7B;
            5'd6: block_data[6] = 32'h3593BB80;
            5'd7: block_data[6] = 32'h357CBB84;
            5'd8: block_data[6] = 32'h3564BB88;
            5'd9: block_data[6] = 32'h354CBB8C;
            5'd10: block_data[6] = 32'h3534BB91;
            5'd11: block_data[6] = 32'h351DBB95;
            5'd12: block_data[6] = 32'h3505BB99;
            5'd13: block_data[6] = 32'h34EDBB9D;
            5'd14: block_data[6] = 32'h34D5BBA0;
            5'd15: block_data[6] = 32'h34BDBBA4;
            5'd16: block_data[6] = 32'h34A5BBA8;
            5'd17: block_data[6] = 32'h348DBBAB;
            5'd18: block_data[6] = 32'h3475BBAF;
            5'd19: block_data[6] = 32'h345DBBB2;
            5'd20: block_data[6] = 32'h3444BBB6;
            5'd21: block_data[6] = 32'h342CBBB9;
            5'd22: block_data[6] = 32'h3414BBBC;
            5'd23: block_data[6] = 32'h33F7BBC0;
            5'd24: block_data[6] = 32'h33C6BBC3;
            5'd25: block_data[6] = 32'h3396BBC6;
            5'd26: block_data[6] = 32'h3365BBC9;
            5'd27: block_data[6] = 32'h3334BBCB;
            5'd28: block_data[6] = 32'h3303BBCE;
            5'd29: block_data[6] = 32'h32D2BBD1;
            5'd30: block_data[6] = 32'h32A1BBD4;
            5'd31: block_data[6] = 32'h326FBBD6;
            default: block_data[6] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[7] = 32'h323EBBD9;
            5'd1: block_data[7] = 32'h320DBBDB;
            5'd2: block_data[7] = 32'h31DBBBDD;
            5'd3: block_data[7] = 32'h31AABBE0;
            5'd4: block_data[7] = 32'h3179BBE2;
            5'd5: block_data[7] = 32'h3147BBE4;
            5'd6: block_data[7] = 32'h3115BBE6;
            5'd7: block_data[7] = 32'h30E4BBE8;
            5'd8: block_data[7] = 32'h30B2BBEA;
            5'd9: block_data[7] = 32'h3080BBEC;
            5'd10: block_data[7] = 32'h304EBBED;
            5'd11: block_data[7] = 32'h301DBBEF;
            5'd12: block_data[7] = 32'h2FD6BBF1;
            5'd13: block_data[7] = 32'h2F72BBF2;
            5'd14: block_data[7] = 32'h2F0EBBF4;
            5'd15: block_data[7] = 32'h2EAABBF5;
            5'd16: block_data[7] = 32'h2E46BBF6;
            5'd17: block_data[7] = 32'h2DE2BBF7;
            5'd18: block_data[7] = 32'h2D7EBBF8;
            5'd19: block_data[7] = 32'h2D1ABBF9;
            5'd20: block_data[7] = 32'h2CB5BBFA;
            5'd21: block_data[7] = 32'h2C51BBFB;
            5'd22: block_data[7] = 32'h2BD9BBFC;
            5'd23: block_data[7] = 32'h2B11BBFD;
            5'd24: block_data[7] = 32'h2A48BBFE;
            5'd25: block_data[7] = 32'h297FBBFE;
            5'd26: block_data[7] = 32'h28B6BBFF;
            5'd27: block_data[7] = 32'h27DABBFF;
            5'd28: block_data[7] = 32'h2648BBFF;
            5'd29: block_data[7] = 32'h24B6BC00;
            5'd30: block_data[7] = 32'h2248BC00;
            5'd31: block_data[7] = 32'h1E48BC00;
            default: block_data[7] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[8] = 32'h0000BC00;
            5'd1: block_data[8] = 32'h9E48BC00;
            5'd2: block_data[8] = 32'hA248BC00;
            5'd3: block_data[8] = 32'hA4B6BC00;
            5'd4: block_data[8] = 32'hA648BBFF;
            5'd5: block_data[8] = 32'hA7DABBFF;
            5'd6: block_data[8] = 32'hA8B6BBFF;
            5'd7: block_data[8] = 32'hA97FBBFE;
            5'd8: block_data[8] = 32'hAA48BBFE;
            5'd9: block_data[8] = 32'hAB11BBFD;
            5'd10: block_data[8] = 32'hABD9BBFC;
            5'd11: block_data[8] = 32'hAC51BBFB;
            5'd12: block_data[8] = 32'hACB5BBFA;
            5'd13: block_data[8] = 32'hAD1ABBF9;
            5'd14: block_data[8] = 32'hAD7EBBF8;
            5'd15: block_data[8] = 32'hADE2BBF7;
            5'd16: block_data[8] = 32'hAE46BBF6;
            5'd17: block_data[8] = 32'hAEAABBF5;
            5'd18: block_data[8] = 32'hAF0EBBF4;
            5'd19: block_data[8] = 32'hAF72BBF2;
            5'd20: block_data[8] = 32'hAFD6BBF1;
            5'd21: block_data[8] = 32'hB01DBBEF;
            5'd22: block_data[8] = 32'hB04EBBED;
            5'd23: block_data[8] = 32'hB080BBEC;
            5'd24: block_data[8] = 32'hB0B2BBEA;
            5'd25: block_data[8] = 32'hB0E4BBE8;
            5'd26: block_data[8] = 32'hB115BBE6;
            5'd27: block_data[8] = 32'hB147BBE4;
            5'd28: block_data[8] = 32'hB179BBE2;
            5'd29: block_data[8] = 32'hB1AABBE0;
            5'd30: block_data[8] = 32'hB1DBBBDD;
            5'd31: block_data[8] = 32'hB20DBBDB;
            default: block_data[8] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[9] = 32'hB23EBBD9;
            5'd1: block_data[9] = 32'hB26FBBD6;
            5'd2: block_data[9] = 32'hB2A1BBD4;
            5'd3: block_data[9] = 32'hB2D2BBD1;
            5'd4: block_data[9] = 32'hB303BBCE;
            5'd5: block_data[9] = 32'hB334BBCB;
            5'd6: block_data[9] = 32'hB365BBC9;
            5'd7: block_data[9] = 32'hB396BBC6;
            5'd8: block_data[9] = 32'hB3C6BBC3;
            5'd9: block_data[9] = 32'hB3F7BBC0;
            5'd10: block_data[9] = 32'hB414BBBC;
            5'd11: block_data[9] = 32'hB42CBBB9;
            5'd12: block_data[9] = 32'hB444BBB6;
            5'd13: block_data[9] = 32'hB45DBBB2;
            5'd14: block_data[9] = 32'hB475BBAF;
            5'd15: block_data[9] = 32'hB48DBBAB;
            5'd16: block_data[9] = 32'hB4A5BBA8;
            5'd17: block_data[9] = 32'hB4BDBBA4;
            5'd18: block_data[9] = 32'hB4D5BBA0;
            5'd19: block_data[9] = 32'hB4EDBB9D;
            5'd20: block_data[9] = 32'hB505BB99;
            5'd21: block_data[9] = 32'hB51DBB95;
            5'd22: block_data[9] = 32'hB534BB91;
            5'd23: block_data[9] = 32'hB54CBB8C;
            5'd24: block_data[9] = 32'hB564BB88;
            5'd25: block_data[9] = 32'hB57CBB84;
            5'd26: block_data[9] = 32'hB593BB80;
            5'd27: block_data[9] = 32'hB5ABBB7B;
            5'd28: block_data[9] = 32'hB5C2BB77;
            5'd29: block_data[9] = 32'hB5DABB72;
            5'd30: block_data[9] = 32'hB5F1BB6E;
            5'd31: block_data[9] = 32'hB608BB69;
            default: block_data[9] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[10] = 32'hB61FBB64;
            5'd1: block_data[10] = 32'hB637BB5F;
            5'd2: block_data[10] = 32'hB64EBB5A;
            5'd3: block_data[10] = 32'hB665BB55;
            5'd4: block_data[10] = 32'hB67CBB50;
            5'd5: block_data[10] = 32'hB693BB4B;
            5'd6: block_data[10] = 32'hB6AABB46;
            5'd7: block_data[10] = 32'hB6C1BB41;
            5'd8: block_data[10] = 32'hB6D7BB3B;
            5'd9: block_data[10] = 32'hB6EEBB36;
            5'd10: block_data[10] = 32'hB705BB30;
            5'd11: block_data[10] = 32'hB71BBB2B;
            5'd12: block_data[10] = 32'hB732BB25;
            5'd13: block_data[10] = 32'hB748BB20;
            5'd14: block_data[10] = 32'hB75EBB1A;
            5'd15: block_data[10] = 32'hB775BB14;
            5'd16: block_data[10] = 32'hB78BBB0E;
            5'd17: block_data[10] = 32'hB7A1BB08;
            5'd18: block_data[10] = 32'hB7B7BB02;
            5'd19: block_data[10] = 32'hB7CDBAFC;
            5'd20: block_data[10] = 32'hB7E3BAF6;
            5'd21: block_data[10] = 32'hB7F9BAF0;
            5'd22: block_data[10] = 32'hB807BAE9;
            5'd23: block_data[10] = 32'hB812BAE3;
            5'd24: block_data[10] = 32'hB81DBADD;
            5'd25: block_data[10] = 32'hB828BAD6;
            5'd26: block_data[10] = 32'hB832BAD0;
            5'd27: block_data[10] = 32'hB83DBAC9;
            5'd28: block_data[10] = 32'hB848BAC2;
            5'd29: block_data[10] = 32'hB852BABC;
            5'd30: block_data[10] = 32'hB85DBAB5;
            5'd31: block_data[10] = 32'hB867BAAE;
            default: block_data[10] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[11] = 32'hB872BAA7;
            5'd1: block_data[11] = 32'hB87CBAA0;
            5'd2: block_data[11] = 32'hB887BA99;
            5'd3: block_data[11] = 32'hB891BA92;
            5'd4: block_data[11] = 32'hB89BBA8A;
            5'd5: block_data[11] = 32'hB8A6BA83;
            5'd6: block_data[11] = 32'hB8B0BA7C;
            5'd7: block_data[11] = 32'hB8BABA74;
            5'd8: block_data[11] = 32'hB8C4BA6D;
            5'd9: block_data[11] = 32'hB8CEBA65;
            5'd10: block_data[11] = 32'hB8D8BA5E;
            5'd11: block_data[11] = 32'hB8E2BA56;
            5'd12: block_data[11] = 32'hB8ECBA4F;
            5'd13: block_data[11] = 32'hB8F6BA47;
            5'd14: block_data[11] = 32'hB900BA3F;
            5'd15: block_data[11] = 32'hB909BA37;
            5'd16: block_data[11] = 32'hB913BA2F;
            5'd17: block_data[11] = 32'hB91DBA27;
            5'd18: block_data[11] = 32'hB927BA1F;
            5'd19: block_data[11] = 32'hB930BA17;
            5'd20: block_data[11] = 32'hB93ABA0F;
            5'd21: block_data[11] = 32'hB943BA07;
            5'd22: block_data[11] = 32'hB94DB9FE;
            5'd23: block_data[11] = 32'hB956B9F6;
            5'd24: block_data[11] = 32'hB95FB9ED;
            5'd25: block_data[11] = 32'hB969B9E5;
            5'd26: block_data[11] = 32'hB972B9DC;
            5'd27: block_data[11] = 32'hB97BB9D4;
            5'd28: block_data[11] = 32'hB984B9CB;
            5'd29: block_data[11] = 32'hB98DB9C3;
            5'd30: block_data[11] = 32'hB996B9BA;
            5'd31: block_data[11] = 32'hB99FB9B1;
            default: block_data[11] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[12] = 32'hB9A8B9A8;
            5'd1: block_data[12] = 32'hB9B1B99F;
            5'd2: block_data[12] = 32'hB9BAB996;
            5'd3: block_data[12] = 32'hB9C3B98D;
            5'd4: block_data[12] = 32'hB9CBB984;
            5'd5: block_data[12] = 32'hB9D4B97B;
            5'd6: block_data[12] = 32'hB9DCB972;
            5'd7: block_data[12] = 32'hB9E5B969;
            5'd8: block_data[12] = 32'hB9EDB95F;
            5'd9: block_data[12] = 32'hB9F6B956;
            5'd10: block_data[12] = 32'hB9FEB94D;
            5'd11: block_data[12] = 32'hBA07B943;
            5'd12: block_data[12] = 32'hBA0FB93A;
            5'd13: block_data[12] = 32'hBA17B930;
            5'd14: block_data[12] = 32'hBA1FB927;
            5'd15: block_data[12] = 32'hBA27B91D;
            5'd16: block_data[12] = 32'hBA2FB913;
            5'd17: block_data[12] = 32'hBA37B909;
            5'd18: block_data[12] = 32'hBA3FB900;
            5'd19: block_data[12] = 32'hBA47B8F6;
            5'd20: block_data[12] = 32'hBA4FB8EC;
            5'd21: block_data[12] = 32'hBA56B8E2;
            5'd22: block_data[12] = 32'hBA5EB8D8;
            5'd23: block_data[12] = 32'hBA65B8CE;
            5'd24: block_data[12] = 32'hBA6DB8C4;
            5'd25: block_data[12] = 32'hBA74B8BA;
            5'd26: block_data[12] = 32'hBA7CB8B0;
            5'd27: block_data[12] = 32'hBA83B8A6;
            5'd28: block_data[12] = 32'hBA8AB89B;
            5'd29: block_data[12] = 32'hBA92B891;
            5'd30: block_data[12] = 32'hBA99B887;
            5'd31: block_data[12] = 32'hBAA0B87C;
            default: block_data[12] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[13] = 32'hBAA7B872;
            5'd1: block_data[13] = 32'hBAAEB867;
            5'd2: block_data[13] = 32'hBAB5B85D;
            5'd3: block_data[13] = 32'hBABCB852;
            5'd4: block_data[13] = 32'hBAC2B848;
            5'd5: block_data[13] = 32'hBAC9B83D;
            5'd6: block_data[13] = 32'hBAD0B832;
            5'd7: block_data[13] = 32'hBAD6B828;
            5'd8: block_data[13] = 32'hBADDB81D;
            5'd9: block_data[13] = 32'hBAE3B812;
            5'd10: block_data[13] = 32'hBAE9B807;
            5'd11: block_data[13] = 32'hBAF0B7F9;
            5'd12: block_data[13] = 32'hBAF6B7E3;
            5'd13: block_data[13] = 32'hBAFCB7CD;
            5'd14: block_data[13] = 32'hBB02B7B7;
            5'd15: block_data[13] = 32'hBB08B7A1;
            5'd16: block_data[13] = 32'hBB0EB78B;
            5'd17: block_data[13] = 32'hBB14B775;
            5'd18: block_data[13] = 32'hBB1AB75E;
            5'd19: block_data[13] = 32'hBB20B748;
            5'd20: block_data[13] = 32'hBB25B732;
            5'd21: block_data[13] = 32'hBB2BB71B;
            5'd22: block_data[13] = 32'hBB30B705;
            5'd23: block_data[13] = 32'hBB36B6EE;
            5'd24: block_data[13] = 32'hBB3BB6D7;
            5'd25: block_data[13] = 32'hBB41B6C1;
            5'd26: block_data[13] = 32'hBB46B6AA;
            5'd27: block_data[13] = 32'hBB4BB693;
            5'd28: block_data[13] = 32'hBB50B67C;
            5'd29: block_data[13] = 32'hBB55B665;
            5'd30: block_data[13] = 32'hBB5AB64E;
            5'd31: block_data[13] = 32'hBB5FB637;
            default: block_data[13] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[14] = 32'hBB64B61F;
            5'd1: block_data[14] = 32'hBB69B608;
            5'd2: block_data[14] = 32'hBB6EB5F1;
            5'd3: block_data[14] = 32'hBB72B5DA;
            5'd4: block_data[14] = 32'hBB77B5C2;
            5'd5: block_data[14] = 32'hBB7BB5AB;
            5'd6: block_data[14] = 32'hBB80B593;
            5'd7: block_data[14] = 32'hBB84B57C;
            5'd8: block_data[14] = 32'hBB88B564;
            5'd9: block_data[14] = 32'hBB8CB54C;
            5'd10: block_data[14] = 32'hBB91B534;
            5'd11: block_data[14] = 32'hBB95B51D;
            5'd12: block_data[14] = 32'hBB99B505;
            5'd13: block_data[14] = 32'hBB9DB4ED;
            5'd14: block_data[14] = 32'hBBA0B4D5;
            5'd15: block_data[14] = 32'hBBA4B4BD;
            5'd16: block_data[14] = 32'hBBA8B4A5;
            5'd17: block_data[14] = 32'hBBABB48D;
            5'd18: block_data[14] = 32'hBBAFB475;
            5'd19: block_data[14] = 32'hBBB2B45D;
            5'd20: block_data[14] = 32'hBBB6B444;
            5'd21: block_data[14] = 32'hBBB9B42C;
            5'd22: block_data[14] = 32'hBBBCB414;
            5'd23: block_data[14] = 32'hBBC0B3F7;
            5'd24: block_data[14] = 32'hBBC3B3C6;
            5'd25: block_data[14] = 32'hBBC6B396;
            5'd26: block_data[14] = 32'hBBC9B365;
            5'd27: block_data[14] = 32'hBBCBB334;
            5'd28: block_data[14] = 32'hBBCEB303;
            5'd29: block_data[14] = 32'hBBD1B2D2;
            5'd30: block_data[14] = 32'hBBD4B2A1;
            5'd31: block_data[14] = 32'hBBD6B26F;
            default: block_data[14] = 32'h00000000;
        endcase
    end

    always @(*) begin
        case (rom_addr[4:0])
            5'd0: block_data[15] = 32'hBBD9B23E;
            5'd1: block_data[15] = 32'hBBDBB20D;
            5'd2: block_data[15] = 32'hBBDDB1DB;
            5'd3: block_data[15] = 32'hBBE0B1AA;
            5'd4: block_data[15] = 32'hBBE2B179;
            5'd5: block_data[15] = 32'hBBE4B147;
            5'd6: block_data[15] = 32'hBBE6B115;
            5'd7: block_data[15] = 32'hBBE8B0E4;
            5'd8: block_data[15] = 32'hBBEAB0B2;
            5'd9: block_data[15] = 32'hBBECB080;
            5'd10: block_data[15] = 32'hBBEDB04E;
            5'd11: block_data[15] = 32'hBBEFB01D;
            5'd12: block_data[15] = 32'hBBF1AFD6;
            5'd13: block_data[15] = 32'hBBF2AF72;
            5'd14: block_data[15] = 32'hBBF4AF0E;
            5'd15: block_data[15] = 32'hBBF5AEAA;
            5'd16: block_data[15] = 32'hBBF6AE46;
            5'd17: block_data[15] = 32'hBBF7ADE2;
            5'd18: block_data[15] = 32'hBBF8AD7E;
            5'd19: block_data[15] = 32'hBBF9AD1A;
            5'd20: block_data[15] = 32'hBBFAACB5;
            5'd21: block_data[15] = 32'hBBFBAC51;
            5'd22: block_data[15] = 32'hBBFCABD9;
            5'd23: block_data[15] = 32'hBBFDAB11;
            5'd24: block_data[15] = 32'hBBFEAA48;
            5'd25: block_data[15] = 32'hBBFEA97F;
            5'd26: block_data[15] = 32'hBBFFA8B6;
            5'd27: block_data[15] = 32'hBBFFA7DA;
            5'd28: block_data[15] = 32'hBBFFA648;
            5'd29: block_data[15] = 32'hBC00A4B6;
            5'd30: block_data[15] = 32'hBC00A248;
            5'd31: block_data[15] = 32'hBC009E48;
            default: block_data[15] = 32'h00000000;
        endcase
    end

    reg [31:0] raw_data;

    always @(*) begin
        raw_data = block_data[rom_addr[8:5]];
    end

    // --------------------------------------------------------
    // 4. Output Generation
    // --------------------------------------------------------
    always @(*) begin
        if (is_midpoint) begin
            // Hardcoded -1.0 (real = -1.0 -> 0xBC00, imag = +0.0 -> 0x0000)
            twiddle_out = 32'hBC00_0000;
        end else begin
            twiddle_out = raw_data;

            // Apply conjugate (flip the sign of the imaginary part)
            if (use_conjugate) begin
                if (twiddle_out[15:0] != 16'h0000)
                    twiddle_out[15:0] = {~twiddle_out[15], twiddle_out[14:0]};
            end
        end
    end

endmodule
